begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|cmsadapter
operator|.
name|servicesapi
operator|.
name|model
operator|.
name|web
operator|.
name|decorated
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|cmsadapter
operator|.
name|servicesapi
operator|.
name|model
operator|.
name|web
operator|.
name|ObjectTypeDefinition
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|cmsadapter
operator|.
name|servicesapi
operator|.
name|repository
operator|.
name|RepositoryAccessException
import|;
end_import

begin_interface
specifier|public
interface|interface
name|DObjectType
block|{
name|String
name|getID
parameter_list|()
function_decl|;
name|String
name|getName
parameter_list|()
function_decl|;
name|String
name|getNamespace
parameter_list|()
function_decl|;
name|List
argument_list|<
name|DPropertyDefinition
argument_list|>
name|getPropertyDefinitions
parameter_list|()
throws|throws
name|RepositoryAccessException
function_decl|;
name|List
argument_list|<
name|DObjectType
argument_list|>
name|getParentDefinitions
parameter_list|()
throws|throws
name|RepositoryAccessException
function_decl|;
name|List
argument_list|<
name|DObjectType
argument_list|>
name|getChildDefinitions
parameter_list|()
throws|throws
name|RepositoryAccessException
function_decl|;
name|ObjectTypeDefinition
name|getInstance
parameter_list|()
function_decl|;
block|}
end_interface

end_unit

