begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|nlp
operator|.
name|morpho
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|nlp
operator|.
name|model
operator|.
name|Token
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|nlp
operator|.
name|model
operator|.
name|tag
operator|.
name|Tag
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|nlp
operator|.
name|model
operator|.
name|tag
operator|.
name|TagSet
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|servicesapi
operator|.
name|EnhancementEngine
import|;
end_import

begin_comment
comment|/**  * An VerbMood tag typically assigned by a Morphological Analyzer (an  * NLP component) to a {@link Token}<p>  * @author Alessio Bosca  */
end_comment

begin_class
specifier|public
class|class
name|VerbMoodTag
extends|extends
name|Tag
argument_list|<
name|VerbMoodTag
argument_list|>
block|{
specifier|private
specifier|final
name|VerbMood
name|verbMood
decl_stmt|;
comment|/**      * Creates a new VerbMoodTag for the parsed tag. The created Tag is not      * assigned to any {@link VerbMood}.<p> This constructor can be used      * by {@link EnhancementEngine}s that encounter an Tag they do not know       * (e.g. that is not defined by the configured {@link TagSet}).<p>      * @param tag the Tag      * @throws IllegalArgumentException if the parsed tag is<code>null</code>      * or empty.      */
specifier|public
name|VerbMoodTag
parameter_list|(
name|String
name|tag
parameter_list|)
block|{
name|this
argument_list|(
name|tag
argument_list|,
literal|null
argument_list|)
expr_stmt|;
block|}
comment|/**      * Creates a VerbMoodTag that is assigned to a {@link Case}      * @param tag the tag      * @param verbMood the lexical VerbMood or<code>null</code> if not known      * @throws IllegalArgumentException if the parsed tag is<code>null</code>      * or empty.      */
specifier|public
name|VerbMoodTag
parameter_list|(
name|String
name|tag
parameter_list|,
name|VerbMood
name|verbMood
parameter_list|)
block|{
name|super
argument_list|(
name|tag
argument_list|)
expr_stmt|;
name|this
operator|.
name|verbMood
operator|=
name|verbMood
expr_stmt|;
block|}
comment|/**      * The verbMood of this tag (if known)      * @return the VerbMood or<code>null</code> if not mapped to any      */
specifier|public
name|VerbMood
name|getVerbForm
parameter_list|()
block|{
return|return
name|this
operator|.
name|verbMood
return|;
block|}
annotation|@
name|Override
specifier|public
name|String
name|toString
parameter_list|()
block|{
return|return
name|String
operator|.
name|format
argument_list|(
literal|"VERB FORM %s (%s)"
argument_list|,
name|tag
argument_list|,
name|verbMood
operator|==
literal|null
condition|?
literal|"none"
else|:
name|verbMood
operator|.
name|name
argument_list|()
argument_list|)
return|;
block|}
annotation|@
name|Override
specifier|public
name|int
name|hashCode
parameter_list|()
block|{
return|return
name|tag
operator|.
name|hashCode
argument_list|()
return|;
block|}
annotation|@
name|Override
specifier|public
name|boolean
name|equals
parameter_list|(
name|Object
name|obj
parameter_list|)
block|{
return|return
name|super
operator|.
name|equals
argument_list|(
name|obj
argument_list|)
operator|&&
name|obj
operator|instanceof
name|VerbMoodTag
operator|&&
operator|(
name|verbMood
operator|==
literal|null
operator|&&
operator|(
operator|(
name|VerbMoodTag
operator|)
name|obj
operator|)
operator|.
name|verbMood
operator|==
literal|null
operator|)
operator|||
operator|(
name|verbMood
operator|!=
literal|null
operator|&&
name|verbMood
operator|.
name|equals
argument_list|(
operator|(
operator|(
name|VerbMoodTag
operator|)
name|obj
operator|)
operator|.
name|verbMood
argument_list|)
operator|)
return|;
block|}
block|}
end_class

end_unit

