begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|engines
operator|.
name|opennlp
operator|.
name|impl
package|;
end_package

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|servicesapi
operator|.
name|rdf
operator|.
name|Properties
operator|.
name|DC_RELATION
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|servicesapi
operator|.
name|rdf
operator|.
name|Properties
operator|.
name|DC_TYPE
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|servicesapi
operator|.
name|rdf
operator|.
name|Properties
operator|.
name|ENHANCER_CONFIDENCE
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|servicesapi
operator|.
name|rdf
operator|.
name|Properties
operator|.
name|ENHANCER_END
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|servicesapi
operator|.
name|rdf
operator|.
name|Properties
operator|.
name|ENHANCER_SELECTED_TEXT
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|servicesapi
operator|.
name|rdf
operator|.
name|Properties
operator|.
name|ENHANCER_SELECTION_CONTEXT
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|servicesapi
operator|.
name|rdf
operator|.
name|Properties
operator|.
name|ENHANCER_START
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_import
import|import
name|java
operator|.
name|nio
operator|.
name|charset
operator|.
name|Charset
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|ArrayList
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Collection
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Collections
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|HashMap
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Iterator
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|LinkedHashMap
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Map
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Map
operator|.
name|Entry
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Set
import|;
end_import

begin_import
import|import
name|opennlp
operator|.
name|tools
operator|.
name|namefind
operator|.
name|NameFinderME
import|;
end_import

begin_import
import|import
name|opennlp
operator|.
name|tools
operator|.
name|namefind
operator|.
name|TokenNameFinderModel
import|;
end_import

begin_import
import|import
name|opennlp
operator|.
name|tools
operator|.
name|sentdetect
operator|.
name|SentenceDetectorME
import|;
end_import

begin_import
import|import
name|opennlp
operator|.
name|tools
operator|.
name|sentdetect
operator|.
name|SentenceModel
import|;
end_import

begin_import
import|import
name|opennlp
operator|.
name|tools
operator|.
name|tokenize
operator|.
name|SimpleTokenizer
import|;
end_import

begin_import
import|import
name|opennlp
operator|.
name|tools
operator|.
name|tokenize
operator|.
name|Tokenizer
import|;
end_import

begin_import
import|import
name|opennlp
operator|.
name|tools
operator|.
name|util
operator|.
name|InvalidFormatException
import|;
end_import

begin_import
import|import
name|opennlp
operator|.
name|tools
operator|.
name|util
operator|.
name|Span
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|clerezza
operator|.
name|rdf
operator|.
name|core
operator|.
name|Language
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|clerezza
operator|.
name|rdf
operator|.
name|core
operator|.
name|Literal
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|clerezza
operator|.
name|rdf
operator|.
name|core
operator|.
name|LiteralFactory
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|clerezza
operator|.
name|rdf
operator|.
name|core
operator|.
name|MGraph
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|clerezza
operator|.
name|rdf
operator|.
name|core
operator|.
name|Triple
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|clerezza
operator|.
name|rdf
operator|.
name|core
operator|.
name|UriRef
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|clerezza
operator|.
name|rdf
operator|.
name|core
operator|.
name|impl
operator|.
name|PlainLiteralImpl
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|clerezza
operator|.
name|rdf
operator|.
name|core
operator|.
name|impl
operator|.
name|TripleImpl
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|commons
operator|.
name|io
operator|.
name|IOUtils
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|commons
operator|.
name|lang
operator|.
name|StringUtils
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|commons
operator|.
name|opennlp
operator|.
name|OpenNLP
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|commons
operator|.
name|stanboltools
operator|.
name|datafileprovider
operator|.
name|DataFileProvider
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|servicesapi
operator|.
name|Blob
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|servicesapi
operator|.
name|ContentItem
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|servicesapi
operator|.
name|EngineException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|servicesapi
operator|.
name|EnhancementEngine
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|servicesapi
operator|.
name|InvalidContentException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|servicesapi
operator|.
name|helper
operator|.
name|ContentItemHelper
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|servicesapi
operator|.
name|helper
operator|.
name|EnhancementEngineHelper
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|servicesapi
operator|.
name|rdf
operator|.
name|OntologicalClasses
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|servicesapi
operator|.
name|rdf
operator|.
name|Properties
import|;
end_import

begin_import
import|import
name|org
operator|.
name|slf4j
operator|.
name|Logger
import|;
end_import

begin_import
import|import
name|org
operator|.
name|slf4j
operator|.
name|LoggerFactory
import|;
end_import

begin_comment
comment|/**  * Core of our EnhancementEngine, separated from the OSGi service to make it easier to test this.  */
end_comment

begin_class
specifier|public
class|class
name|NEREngineCore
implements|implements
name|EnhancementEngine
block|{
specifier|protected
specifier|static
specifier|final
name|String
name|TEXT_PLAIN_MIMETYPE
init|=
literal|"text/plain"
decl_stmt|;
comment|/**      * Contains the only supported mimetype {@link #TEXT_PLAIN_MIMETYPE}      */
specifier|protected
specifier|static
specifier|final
name|Set
argument_list|<
name|String
argument_list|>
name|SUPPORTED_MIMETYPES
init|=
name|Collections
operator|.
name|singleton
argument_list|(
name|TEXT_PLAIN_MIMETYPE
argument_list|)
decl_stmt|;
specifier|private
specifier|final
name|Logger
name|log
init|=
name|LoggerFactory
operator|.
name|getLogger
argument_list|(
name|getClass
argument_list|()
argument_list|)
decl_stmt|;
specifier|private
specifier|static
name|Map
argument_list|<
name|String
argument_list|,
name|UriRef
argument_list|>
name|entityTypes
init|=
operator|new
name|HashMap
argument_list|<
name|String
argument_list|,
name|UriRef
argument_list|>
argument_list|()
decl_stmt|;
static|static
block|{
name|entityTypes
operator|.
name|put
argument_list|(
literal|"person"
argument_list|,
name|OntologicalClasses
operator|.
name|DBPEDIA_PERSON
argument_list|)
expr_stmt|;
name|entityTypes
operator|.
name|put
argument_list|(
literal|"location"
argument_list|,
name|OntologicalClasses
operator|.
name|DBPEDIA_PLACE
argument_list|)
expr_stmt|;
name|entityTypes
operator|.
name|put
argument_list|(
literal|"organization"
argument_list|,
name|OntologicalClasses
operator|.
name|DBPEDIA_ORGANISATION
argument_list|)
expr_stmt|;
block|}
specifier|private
name|OpenNLP
name|openNLP
decl_stmt|;
specifier|private
specifier|final
name|String
name|defaultLang
decl_stmt|;
specifier|private
specifier|final
name|Set
argument_list|<
name|String
argument_list|>
name|processedLangs
decl_stmt|;
comment|/** Comments about our models */
specifier|public
specifier|static
specifier|final
name|Map
argument_list|<
name|String
argument_list|,
name|String
argument_list|>
name|DATA_FILE_COMMENTS
decl_stmt|;
static|static
block|{
name|DATA_FILE_COMMENTS
operator|=
operator|new
name|HashMap
argument_list|<
name|String
argument_list|,
name|String
argument_list|>
argument_list|()
expr_stmt|;
name|DATA_FILE_COMMENTS
operator|.
name|put
argument_list|(
literal|"Default data files"
argument_list|,
literal|"provided by the org.apache.stanbol.defaultdata bundle"
argument_list|)
expr_stmt|;
block|}
specifier|public
name|NEREngineCore
parameter_list|(
name|OpenNLP
name|openNLP
parameter_list|,
name|String
name|defaultLanguage
parameter_list|,
name|Set
argument_list|<
name|String
argument_list|>
name|processedLanguages
parameter_list|)
throws|throws
name|InvalidFormatException
throws|,
name|IOException
block|{
name|this
operator|.
name|openNLP
operator|=
name|openNLP
expr_stmt|;
name|this
operator|.
name|defaultLang
operator|=
name|defaultLanguage
expr_stmt|;
name|this
operator|.
name|processedLangs
operator|=
name|Collections
operator|.
name|unmodifiableSet
argument_list|(
name|processedLanguages
argument_list|)
expr_stmt|;
block|}
name|NEREngineCore
parameter_list|(
name|DataFileProvider
name|dfp
parameter_list|,
name|String
name|defaultLanguage
parameter_list|,
name|Set
argument_list|<
name|String
argument_list|>
name|processedLanguages
parameter_list|)
throws|throws
name|InvalidFormatException
throws|,
name|IOException
block|{
name|this
argument_list|(
operator|new
name|OpenNLP
argument_list|(
name|dfp
argument_list|)
argument_list|,
name|defaultLanguage
argument_list|,
name|processedLanguages
argument_list|)
expr_stmt|;
block|}
comment|//    protected TokenNameFinderModel buildNameModel(String name, UriRef typeUri) throws IOException {
comment|//        //String modelRelativePath = String.format("en-ner-%s.bin", name);
comment|//        TokenNameFinderModel model = openNLP.getNameModel(name, "en");
comment|//        // register the name finder instances for matching owl class
comment|////        entityTypes.put(name, new Object[] {typeUri, model});
comment|//        return model;
comment|//    }
annotation|@
name|Override
specifier|public
name|String
name|getName
parameter_list|()
block|{
return|return
name|getClass
argument_list|()
operator|.
name|getName
argument_list|()
return|;
block|}
specifier|public
name|void
name|computeEnhancements
parameter_list|(
name|ContentItem
name|ci
parameter_list|)
throws|throws
name|EngineException
block|{
comment|//first check the langauge before processing the content (text)
name|String
name|language
init|=
name|extractLanguage
argument_list|(
name|ci
argument_list|)
decl_stmt|;
if|if
condition|(
name|language
operator|==
literal|null
condition|)
block|{
throw|throw
operator|new
name|IllegalStateException
argument_list|(
literal|"Unable to extract Language for "
operator|+
literal|"ContentItem "
operator|+
name|ci
operator|.
name|getUri
argument_list|()
operator|+
literal|": This is also checked in the canEnhance "
operator|+
literal|"method! -> This indicated an Bug in the implementation of the "
operator|+
literal|"EnhancementJobManager!"
argument_list|)
throw|;
block|}
if|if
condition|(
operator|!
name|isProcessedLangage
argument_list|(
name|language
argument_list|)
condition|)
block|{
throw|throw
operator|new
name|IllegalStateException
argument_list|(
literal|"The language '"
operator|+
name|language
operator|+
literal|"' of ContentItem "
operator|+
name|ci
operator|.
name|getUri
argument_list|()
operator|+
literal|" is not configured to be processed by this NER engine instance "
operator|+
literal|"(processed "
operator|+
name|processedLangs
operator|+
literal|"): This is also checked in the canEnhance "
operator|+
literal|"method! -> This indicated an Bug in the implementation of the "
operator|+
literal|"EnhancementJobManager!"
argument_list|)
throw|;
block|}
name|Entry
argument_list|<
name|UriRef
argument_list|,
name|Blob
argument_list|>
name|contentPart
init|=
name|ContentItemHelper
operator|.
name|getBlob
argument_list|(
name|ci
argument_list|,
name|SUPPORTED_MIMETYPES
argument_list|)
decl_stmt|;
if|if
condition|(
name|contentPart
operator|==
literal|null
condition|)
block|{
throw|throw
operator|new
name|IllegalStateException
argument_list|(
literal|"No ContentPart with Mimetype '"
operator|+
name|TEXT_PLAIN_MIMETYPE
operator|+
literal|"' found for ContentItem "
operator|+
name|ci
operator|.
name|getUri
argument_list|()
operator|+
literal|": This is also checked in the canEnhance method! -> This "
operator|+
literal|"indicated an Bug in the implementation of the "
operator|+
literal|"EnhancementJobManager!"
argument_list|)
throw|;
block|}
name|String
name|text
decl_stmt|;
try|try
block|{
name|text
operator|=
name|ContentItemHelper
operator|.
name|getText
argument_list|(
name|contentPart
operator|.
name|getValue
argument_list|()
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|IOException
name|e
parameter_list|)
block|{
throw|throw
operator|new
name|InvalidContentException
argument_list|(
name|this
argument_list|,
name|ci
argument_list|,
name|e
argument_list|)
throw|;
block|}
if|if
condition|(
name|text
operator|.
name|trim
argument_list|()
operator|.
name|length
argument_list|()
operator|==
literal|0
condition|)
block|{
comment|// TODO: make the length of the data a field of the ContentItem
comment|// interface to be able to filter out empty items in the canEnhance
comment|// method
name|log
operator|.
name|warn
argument_list|(
literal|"ContentPart {} of ContentItem {} does not contain any text"
operator|+
literal|"to extract knowledge from in ContentItem {}"
argument_list|,
name|contentPart
operator|.
name|getKey
argument_list|()
argument_list|,
name|ci
argument_list|)
expr_stmt|;
return|return;
block|}
name|log
operator|.
name|debug
argument_list|(
literal|"computeEnhancements from ContentPart {} of ContentItem {}: text={}"
argument_list|,
operator|new
name|Object
index|[]
block|{
name|contentPart
operator|.
name|getKey
argument_list|()
block|,
name|ci
operator|.
name|getUri
argument_list|()
operator|.
name|getUnicodeString
argument_list|()
block|,
name|StringUtils
operator|.
name|abbreviate
argument_list|(
name|text
argument_list|,
literal|100
argument_list|)
block|}
argument_list|)
expr_stmt|;
try|try
block|{
for|for
control|(
name|Map
operator|.
name|Entry
argument_list|<
name|String
argument_list|,
name|UriRef
argument_list|>
name|type
range|:
name|entityTypes
operator|.
name|entrySet
argument_list|()
control|)
block|{
name|String
name|typeLabel
init|=
name|type
operator|.
name|getKey
argument_list|()
decl_stmt|;
name|UriRef
name|typeUri
init|=
name|type
operator|.
name|getValue
argument_list|()
decl_stmt|;
name|TokenNameFinderModel
name|nameFinderModel
init|=
name|openNLP
operator|.
name|getNameModel
argument_list|(
name|typeLabel
argument_list|,
name|language
argument_list|)
decl_stmt|;
if|if
condition|(
name|nameFinderModel
operator|==
literal|null
condition|)
block|{
name|log
operator|.
name|info
argument_list|(
literal|"No NER Model for {} and language {} available!"
argument_list|,
name|typeLabel
argument_list|,
name|language
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|findNamedEntities
argument_list|(
name|ci
argument_list|,
name|text
argument_list|,
name|language
argument_list|,
name|typeUri
argument_list|,
name|typeLabel
argument_list|,
name|nameFinderModel
argument_list|)
expr_stmt|;
block|}
block|}
block|}
catch|catch
parameter_list|(
name|Exception
name|e
parameter_list|)
block|{
if|if
condition|(
name|e
operator|instanceof
name|RuntimeException
condition|)
block|{
throw|throw
operator|(
name|RuntimeException
operator|)
name|e
throw|;
block|}
else|else
block|{
throw|throw
operator|new
name|EngineException
argument_list|(
name|this
argument_list|,
name|ci
argument_list|,
name|e
argument_list|)
throw|;
block|}
block|}
block|}
specifier|protected
name|void
name|findNamedEntities
parameter_list|(
specifier|final
name|ContentItem
name|ci
parameter_list|,
specifier|final
name|String
name|text
parameter_list|,
specifier|final
name|String
name|lang
parameter_list|,
specifier|final
name|UriRef
name|typeUri
parameter_list|,
specifier|final
name|String
name|typeLabel
parameter_list|,
specifier|final
name|TokenNameFinderModel
name|nameFinderModel
parameter_list|)
block|{
if|if
condition|(
name|ci
operator|==
literal|null
condition|)
block|{
throw|throw
operator|new
name|IllegalArgumentException
argument_list|(
literal|"Parsed ContentItem MUST NOT be NULL"
argument_list|)
throw|;
block|}
if|if
condition|(
name|text
operator|==
literal|null
condition|)
block|{
name|log
operator|.
name|warn
argument_list|(
literal|"NULL was parsed as text for content item "
operator|+
name|ci
operator|.
name|getUri
argument_list|()
operator|.
name|getUnicodeString
argument_list|()
operator|+
literal|"! -> call ignored"
argument_list|)
expr_stmt|;
return|return;
block|}
specifier|final
name|Language
name|language
decl_stmt|;
if|if
condition|(
name|lang
operator|!=
literal|null
operator|&&
operator|!
name|lang
operator|.
name|isEmpty
argument_list|()
condition|)
block|{
name|language
operator|=
operator|new
name|Language
argument_list|(
name|lang
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|language
operator|=
literal|null
expr_stmt|;
block|}
name|log
operator|.
name|debug
argument_list|(
literal|"findNamedEntities typeUri={}, type={}, text="
argument_list|,
operator|new
name|Object
index|[]
block|{
name|typeUri
block|,
name|typeLabel
block|,
name|StringUtils
operator|.
name|abbreviate
argument_list|(
name|text
argument_list|,
literal|100
argument_list|)
block|}
argument_list|)
expr_stmt|;
name|LiteralFactory
name|literalFactory
init|=
name|LiteralFactory
operator|.
name|getInstance
argument_list|()
decl_stmt|;
name|MGraph
name|g
init|=
name|ci
operator|.
name|getMetadata
argument_list|()
decl_stmt|;
name|Map
argument_list|<
name|String
argument_list|,
name|List
argument_list|<
name|NameOccurrence
argument_list|>
argument_list|>
name|entityNames
init|=
name|extractNameOccurrences
argument_list|(
name|nameFinderModel
argument_list|,
name|text
argument_list|)
decl_stmt|;
comment|//lock the ContentItem while writing the RDF data for found Named Entities
name|ci
operator|.
name|getLock
argument_list|()
operator|.
name|writeLock
argument_list|()
operator|.
name|lock
argument_list|()
expr_stmt|;
try|try
block|{
name|Map
argument_list|<
name|String
argument_list|,
name|UriRef
argument_list|>
name|previousAnnotations
init|=
operator|new
name|LinkedHashMap
argument_list|<
name|String
argument_list|,
name|UriRef
argument_list|>
argument_list|()
decl_stmt|;
for|for
control|(
name|Map
operator|.
name|Entry
argument_list|<
name|String
argument_list|,
name|List
argument_list|<
name|NameOccurrence
argument_list|>
argument_list|>
name|nameInContext
range|:
name|entityNames
operator|.
name|entrySet
argument_list|()
control|)
block|{
name|String
name|name
init|=
name|nameInContext
operator|.
name|getKey
argument_list|()
decl_stmt|;
name|List
argument_list|<
name|NameOccurrence
argument_list|>
name|occurrences
init|=
name|nameInContext
operator|.
name|getValue
argument_list|()
decl_stmt|;
name|UriRef
name|firstOccurrenceAnnotation
init|=
literal|null
decl_stmt|;
for|for
control|(
name|NameOccurrence
name|occurrence
range|:
name|occurrences
control|)
block|{
name|UriRef
name|textAnnotation
init|=
name|EnhancementEngineHelper
operator|.
name|createTextEnhancement
argument_list|(
name|ci
argument_list|,
name|this
argument_list|)
decl_stmt|;
name|g
operator|.
name|add
argument_list|(
operator|new
name|TripleImpl
argument_list|(
name|textAnnotation
argument_list|,
name|ENHANCER_SELECTED_TEXT
argument_list|,
operator|new
name|PlainLiteralImpl
argument_list|(
name|name
argument_list|,
name|language
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
name|g
operator|.
name|add
argument_list|(
operator|new
name|TripleImpl
argument_list|(
name|textAnnotation
argument_list|,
name|ENHANCER_SELECTION_CONTEXT
argument_list|,
operator|new
name|PlainLiteralImpl
argument_list|(
name|occurrence
operator|.
name|context
argument_list|,
name|language
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
name|g
operator|.
name|add
argument_list|(
operator|new
name|TripleImpl
argument_list|(
name|textAnnotation
argument_list|,
name|DC_TYPE
argument_list|,
name|typeUri
argument_list|)
argument_list|)
expr_stmt|;
name|g
operator|.
name|add
argument_list|(
operator|new
name|TripleImpl
argument_list|(
name|textAnnotation
argument_list|,
name|ENHANCER_CONFIDENCE
argument_list|,
name|literalFactory
operator|.
name|createTypedLiteral
argument_list|(
name|occurrence
operator|.
name|confidence
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
name|occurrence
operator|.
name|start
operator|!=
literal|null
operator|&&
name|occurrence
operator|.
name|end
operator|!=
literal|null
condition|)
block|{
name|g
operator|.
name|add
argument_list|(
operator|new
name|TripleImpl
argument_list|(
name|textAnnotation
argument_list|,
name|ENHANCER_START
argument_list|,
name|literalFactory
operator|.
name|createTypedLiteral
argument_list|(
name|occurrence
operator|.
name|start
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
name|g
operator|.
name|add
argument_list|(
operator|new
name|TripleImpl
argument_list|(
name|textAnnotation
argument_list|,
name|ENHANCER_END
argument_list|,
name|literalFactory
operator|.
name|createTypedLiteral
argument_list|(
name|occurrence
operator|.
name|end
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
block|}
comment|// add the subsumption relationship among occurrences of the same
comment|// name
if|if
condition|(
name|firstOccurrenceAnnotation
operator|==
literal|null
condition|)
block|{
comment|// check already extracted annotations to find a first most
comment|// specific occurrence
for|for
control|(
name|Map
operator|.
name|Entry
argument_list|<
name|String
argument_list|,
name|UriRef
argument_list|>
name|entry
range|:
name|previousAnnotations
operator|.
name|entrySet
argument_list|()
control|)
block|{
if|if
condition|(
name|entry
operator|.
name|getKey
argument_list|()
operator|.
name|contains
argument_list|(
name|name
argument_list|)
condition|)
block|{
comment|// we have found a most specific previous
comment|// occurrence, use it as subsumption target
name|firstOccurrenceAnnotation
operator|=
name|entry
operator|.
name|getValue
argument_list|()
expr_stmt|;
name|g
operator|.
name|add
argument_list|(
operator|new
name|TripleImpl
argument_list|(
name|textAnnotation
argument_list|,
name|DC_RELATION
argument_list|,
name|firstOccurrenceAnnotation
argument_list|)
argument_list|)
expr_stmt|;
break|break;
block|}
block|}
if|if
condition|(
name|firstOccurrenceAnnotation
operator|==
literal|null
condition|)
block|{
comment|// no most specific previous occurrence, I am the first,
comment|// most specific occurrence to be later used as a target
name|firstOccurrenceAnnotation
operator|=
name|textAnnotation
expr_stmt|;
name|previousAnnotations
operator|.
name|put
argument_list|(
name|name
argument_list|,
name|textAnnotation
argument_list|)
expr_stmt|;
block|}
block|}
else|else
block|{
comment|// I am referring to a most specific first occurrence of the
comment|// same name
name|g
operator|.
name|add
argument_list|(
operator|new
name|TripleImpl
argument_list|(
name|textAnnotation
argument_list|,
name|DC_RELATION
argument_list|,
name|firstOccurrenceAnnotation
argument_list|)
argument_list|)
expr_stmt|;
block|}
block|}
block|}
block|}
finally|finally
block|{
name|ci
operator|.
name|getLock
argument_list|()
operator|.
name|writeLock
argument_list|()
operator|.
name|unlock
argument_list|()
expr_stmt|;
block|}
block|}
specifier|public
name|Collection
argument_list|<
name|String
argument_list|>
name|extractPersonNames
parameter_list|(
name|String
name|text
parameter_list|)
block|{
return|return
name|extractNames
argument_list|(
name|getNameModel
argument_list|(
literal|"person"
argument_list|,
literal|"en"
argument_list|)
argument_list|,
name|text
argument_list|)
return|;
block|}
specifier|public
name|Collection
argument_list|<
name|String
argument_list|>
name|extractLocationNames
parameter_list|(
name|String
name|text
parameter_list|)
block|{
return|return
name|extractNames
argument_list|(
name|getNameModel
argument_list|(
literal|"location"
argument_list|,
literal|"en"
argument_list|)
argument_list|,
name|text
argument_list|)
return|;
block|}
specifier|public
name|Collection
argument_list|<
name|String
argument_list|>
name|extractOrganizationNames
parameter_list|(
name|String
name|text
parameter_list|)
block|{
return|return
name|extractNames
argument_list|(
name|getNameModel
argument_list|(
literal|"organization"
argument_list|,
literal|"en"
argument_list|)
argument_list|,
name|text
argument_list|)
return|;
block|}
specifier|public
name|Map
argument_list|<
name|String
argument_list|,
name|List
argument_list|<
name|NameOccurrence
argument_list|>
argument_list|>
name|extractPersonNameOccurrences
parameter_list|(
name|String
name|text
parameter_list|)
block|{
return|return
name|extractNameOccurrences
argument_list|(
name|getNameModel
argument_list|(
literal|"person"
argument_list|,
literal|"en"
argument_list|)
argument_list|,
name|text
argument_list|)
return|;
block|}
specifier|public
name|Map
argument_list|<
name|String
argument_list|,
name|List
argument_list|<
name|NameOccurrence
argument_list|>
argument_list|>
name|extractLocationNameOccurrences
parameter_list|(
name|String
name|text
parameter_list|)
block|{
return|return
name|extractNameOccurrences
argument_list|(
name|getNameModel
argument_list|(
literal|"location"
argument_list|,
literal|"en"
argument_list|)
argument_list|,
name|text
argument_list|)
return|;
block|}
specifier|public
name|Map
argument_list|<
name|String
argument_list|,
name|List
argument_list|<
name|NameOccurrence
argument_list|>
argument_list|>
name|extractOrganizationNameOccurrences
parameter_list|(
name|String
name|text
parameter_list|)
block|{
return|return
name|extractNameOccurrences
argument_list|(
name|getNameModel
argument_list|(
literal|"organization"
argument_list|,
literal|"en"
argument_list|)
argument_list|,
name|text
argument_list|)
return|;
block|}
specifier|protected
name|Collection
argument_list|<
name|String
argument_list|>
name|extractNames
parameter_list|(
name|TokenNameFinderModel
name|nameFinderModel
parameter_list|,
name|String
name|text
parameter_list|)
block|{
return|return
name|extractNameOccurrences
argument_list|(
name|nameFinderModel
argument_list|,
name|text
argument_list|)
operator|.
name|keySet
argument_list|()
return|;
block|}
comment|/**      * Gets/builds a TokenNameFinderModel by using {@link #openNLP} and throws      * {@link IllegalStateException}s in case the model could not be built or      * the data for the model where not found.      * @param the type of the named finder model      * @param language the language for the model      * @return the model or an {@link IllegalStateException} if not available      */
specifier|private
name|TokenNameFinderModel
name|getNameModel
parameter_list|(
name|String
name|type
parameter_list|,
name|String
name|language
parameter_list|)
block|{
try|try
block|{
name|TokenNameFinderModel
name|model
init|=
name|openNLP
operator|.
name|getNameModel
argument_list|(
name|type
argument_list|,
name|language
argument_list|)
decl_stmt|;
if|if
condition|(
name|model
operator|!=
literal|null
condition|)
block|{
return|return
name|model
return|;
block|}
else|else
block|{
throw|throw
operator|new
name|IllegalStateException
argument_list|(
name|String
operator|.
name|format
argument_list|(
literal|"Unable to built Model for extracting %s from '%s' language "
operator|+
literal|"texts because the model data could not be loaded."
argument_list|,
name|type
argument_list|,
name|language
argument_list|)
argument_list|)
throw|;
block|}
block|}
catch|catch
parameter_list|(
name|InvalidFormatException
name|e
parameter_list|)
block|{
throw|throw
operator|new
name|IllegalStateException
argument_list|(
name|String
operator|.
name|format
argument_list|(
literal|"Unable to built Model for extracting %s from '%s' language texts."
argument_list|,
name|type
argument_list|,
name|language
argument_list|)
argument_list|,
name|e
argument_list|)
throw|;
block|}
catch|catch
parameter_list|(
name|IOException
name|e
parameter_list|)
block|{
throw|throw
operator|new
name|IllegalStateException
argument_list|(
name|String
operator|.
name|format
argument_list|(
literal|"Unable to built Model for extracting %s from '%s' language texts."
argument_list|,
name|type
argument_list|,
name|language
argument_list|)
argument_list|,
name|e
argument_list|)
throw|;
block|}
block|}
specifier|private
name|SentenceModel
name|getSentenceModel
parameter_list|(
name|String
name|language
parameter_list|)
block|{
try|try
block|{
name|SentenceModel
name|model
init|=
name|openNLP
operator|.
name|getSentenceModel
argument_list|(
name|language
argument_list|)
decl_stmt|;
if|if
condition|(
name|model
operator|!=
literal|null
condition|)
block|{
return|return
name|model
return|;
block|}
else|else
block|{
throw|throw
operator|new
name|IllegalStateException
argument_list|(
name|String
operator|.
name|format
argument_list|(
literal|"Unable to built Model for extracting sentences from '%s' "
operator|+
literal|"language texts because the model data could not be loaded."
argument_list|,
name|language
argument_list|)
argument_list|)
throw|;
block|}
block|}
catch|catch
parameter_list|(
name|InvalidFormatException
name|e
parameter_list|)
block|{
throw|throw
operator|new
name|IllegalStateException
argument_list|(
name|String
operator|.
name|format
argument_list|(
literal|"Unable to built Model for extracting sentences from '%s' language texts."
argument_list|,
name|language
argument_list|)
argument_list|,
name|e
argument_list|)
throw|;
block|}
catch|catch
parameter_list|(
name|IOException
name|e
parameter_list|)
block|{
throw|throw
operator|new
name|IllegalStateException
argument_list|(
name|String
operator|.
name|format
argument_list|(
literal|"Unable to built Model for extracting sentences from '%s' language texts."
argument_list|,
name|language
argument_list|)
argument_list|,
name|e
argument_list|)
throw|;
block|}
block|}
specifier|protected
name|Map
argument_list|<
name|String
argument_list|,
name|List
argument_list|<
name|NameOccurrence
argument_list|>
argument_list|>
name|extractNameOccurrences
parameter_list|(
name|TokenNameFinderModel
name|nameFinderModel
parameter_list|,
name|String
name|text
parameter_list|)
block|{
comment|// version with explicit sentence endings to reflect heading / paragraph
comment|// structure of an HTML or PDF document converted to text
name|String
name|textWithDots
init|=
name|text
operator|.
name|replaceAll
argument_list|(
literal|"\\n\\n"
argument_list|,
literal|".\n"
argument_list|)
decl_stmt|;
name|text
operator|=
name|removeNonUtf8CompliantCharacters
argument_list|(
name|text
argument_list|)
expr_stmt|;
name|SentenceDetectorME
name|sentenceDetector
init|=
operator|new
name|SentenceDetectorME
argument_list|(
name|getSentenceModel
argument_list|(
literal|"en"
argument_list|)
argument_list|)
decl_stmt|;
name|Span
index|[]
name|sentenceSpans
init|=
name|sentenceDetector
operator|.
name|sentPosDetect
argument_list|(
name|textWithDots
argument_list|)
decl_stmt|;
name|NameFinderME
name|finder
init|=
operator|new
name|NameFinderME
argument_list|(
name|nameFinderModel
argument_list|)
decl_stmt|;
name|Tokenizer
name|tokenizer
init|=
name|SimpleTokenizer
operator|.
name|INSTANCE
decl_stmt|;
name|Map
argument_list|<
name|String
argument_list|,
name|List
argument_list|<
name|NameOccurrence
argument_list|>
argument_list|>
name|nameOccurrences
init|=
operator|new
name|LinkedHashMap
argument_list|<
name|String
argument_list|,
name|List
argument_list|<
name|NameOccurrence
argument_list|>
argument_list|>
argument_list|()
decl_stmt|;
for|for
control|(
name|int
name|i
init|=
literal|0
init|;
name|i
operator|<
name|sentenceSpans
operator|.
name|length
condition|;
name|i
operator|++
control|)
block|{
name|String
name|sentence
init|=
name|sentenceSpans
index|[
name|i
index|]
operator|.
name|getCoveredText
argument_list|(
name|text
argument_list|)
operator|.
name|toString
argument_list|()
operator|.
name|trim
argument_list|()
decl_stmt|;
comment|// build a context by concatenating three sentences to be used for
comment|// similarity ranking / disambiguation + contextual snippet in the
comment|// extraction structure
name|List
argument_list|<
name|String
argument_list|>
name|contextElements
init|=
operator|new
name|ArrayList
argument_list|<
name|String
argument_list|>
argument_list|()
decl_stmt|;
if|if
condition|(
name|i
operator|>
literal|0
condition|)
block|{
name|CharSequence
name|previousSentence
init|=
name|sentenceSpans
index|[
name|i
operator|-
literal|1
index|]
operator|.
name|getCoveredText
argument_list|(
name|text
argument_list|)
decl_stmt|;
name|contextElements
operator|.
name|add
argument_list|(
name|previousSentence
operator|.
name|toString
argument_list|()
operator|.
name|trim
argument_list|()
argument_list|)
expr_stmt|;
block|}
name|contextElements
operator|.
name|add
argument_list|(
name|sentence
operator|.
name|toString
argument_list|()
operator|.
name|trim
argument_list|()
argument_list|)
expr_stmt|;
if|if
condition|(
name|i
operator|+
literal|1
operator|<
name|sentenceSpans
operator|.
name|length
condition|)
block|{
name|CharSequence
name|nextSentence
init|=
name|sentenceSpans
index|[
name|i
operator|+
literal|1
index|]
operator|.
name|getCoveredText
argument_list|(
name|text
argument_list|)
decl_stmt|;
name|contextElements
operator|.
name|add
argument_list|(
name|nextSentence
operator|.
name|toString
argument_list|()
operator|.
name|trim
argument_list|()
argument_list|)
expr_stmt|;
block|}
name|String
name|context
init|=
name|StringUtils
operator|.
name|join
argument_list|(
name|contextElements
argument_list|,
literal|" "
argument_list|)
decl_stmt|;
comment|// extract the names in the current sentence and
comment|// keep them store them with the current context
name|Span
index|[]
name|tokenSpans
init|=
name|tokenizer
operator|.
name|tokenizePos
argument_list|(
name|sentence
argument_list|)
decl_stmt|;
name|String
index|[]
name|tokens
init|=
name|Span
operator|.
name|spansToStrings
argument_list|(
name|tokenSpans
argument_list|,
name|sentence
argument_list|)
decl_stmt|;
name|Span
index|[]
name|nameSpans
init|=
name|finder
operator|.
name|find
argument_list|(
name|tokens
argument_list|)
decl_stmt|;
name|double
index|[]
name|probs
init|=
name|finder
operator|.
name|probs
argument_list|()
decl_stmt|;
name|String
index|[]
name|names
init|=
name|Span
operator|.
name|spansToStrings
argument_list|(
name|nameSpans
argument_list|,
name|tokens
argument_list|)
decl_stmt|;
comment|//int lastStartPosition = 0;
for|for
control|(
name|int
name|j
init|=
literal|0
init|;
name|j
operator|<
name|names
operator|.
name|length
condition|;
name|j
operator|++
control|)
block|{
name|String
name|name
init|=
name|names
index|[
name|j
index|]
decl_stmt|;
name|Double
name|confidence
init|=
literal|1.0
decl_stmt|;
for|for
control|(
name|int
name|k
init|=
name|nameSpans
index|[
name|j
index|]
operator|.
name|getStart
argument_list|()
init|;
name|k
operator|<
name|nameSpans
index|[
name|j
index|]
operator|.
name|getEnd
argument_list|()
condition|;
name|k
operator|++
control|)
block|{
name|confidence
operator|*=
name|probs
index|[
name|k
index|]
expr_stmt|;
block|}
name|int
name|start
init|=
name|tokenSpans
index|[
name|nameSpans
index|[
name|j
index|]
operator|.
name|getStart
argument_list|()
index|]
operator|.
name|getStart
argument_list|()
decl_stmt|;
name|int
name|absoluteStart
init|=
name|sentenceSpans
index|[
name|i
index|]
operator|.
name|getStart
argument_list|()
operator|+
name|start
decl_stmt|;
name|int
name|absoluteEnd
init|=
name|absoluteStart
operator|+
name|name
operator|.
name|length
argument_list|()
decl_stmt|;
name|NameOccurrence
name|occurrence
init|=
operator|new
name|NameOccurrence
argument_list|(
name|name
argument_list|,
name|absoluteStart
argument_list|,
name|absoluteEnd
argument_list|,
name|context
argument_list|,
name|confidence
argument_list|)
decl_stmt|;
name|List
argument_list|<
name|NameOccurrence
argument_list|>
name|occurrences
init|=
name|nameOccurrences
operator|.
name|get
argument_list|(
name|name
argument_list|)
decl_stmt|;
if|if
condition|(
name|occurrences
operator|==
literal|null
condition|)
block|{
name|occurrences
operator|=
operator|new
name|ArrayList
argument_list|<
name|NameOccurrence
argument_list|>
argument_list|()
expr_stmt|;
block|}
name|occurrences
operator|.
name|add
argument_list|(
name|occurrence
argument_list|)
expr_stmt|;
name|nameOccurrences
operator|.
name|put
argument_list|(
name|name
argument_list|,
name|occurrences
argument_list|)
expr_stmt|;
block|}
block|}
name|finder
operator|.
name|clearAdaptiveData
argument_list|()
expr_stmt|;
name|log
operator|.
name|debug
argument_list|(
literal|"{} name occurrences found: {}"
argument_list|,
name|nameOccurrences
operator|.
name|size
argument_list|()
argument_list|,
name|nameOccurrences
argument_list|)
expr_stmt|;
return|return
name|nameOccurrences
return|;
block|}
specifier|public
name|int
name|canEnhance
parameter_list|(
name|ContentItem
name|ci
parameter_list|)
block|{
if|if
condition|(
name|ContentItemHelper
operator|.
name|getBlob
argument_list|(
name|ci
argument_list|,
name|SUPPORTED_MIMETYPES
argument_list|)
operator|!=
literal|null
operator|&&
name|isProcessedLangage
argument_list|(
name|extractLanguage
argument_list|(
name|ci
argument_list|)
argument_list|)
condition|)
block|{
return|return
name|ENHANCE_ASYNC
return|;
comment|//The NER engine now supports Async processing!
block|}
return|return
name|CANNOT_ENHANCE
return|;
block|}
comment|/**      * Remove non UTF-8 compliant characters (typically control characters) so has to avoid polluting the      * annotation graph with snippets that are not serializable as XML.      */
specifier|protected
specifier|static
name|String
name|removeNonUtf8CompliantCharacters
parameter_list|(
specifier|final
name|String
name|text
parameter_list|)
block|{
if|if
condition|(
literal|null
operator|==
name|text
condition|)
block|{
return|return
literal|null
return|;
block|}
name|Charset
name|UTF8
init|=
name|Charset
operator|.
name|forName
argument_list|(
literal|"UTF-8"
argument_list|)
decl_stmt|;
name|byte
index|[]
name|bytes
init|=
name|text
operator|.
name|getBytes
argument_list|(
name|UTF8
argument_list|)
decl_stmt|;
for|for
control|(
name|int
name|i
init|=
literal|0
init|;
name|i
operator|<
name|bytes
operator|.
name|length
condition|;
name|i
operator|++
control|)
block|{
name|byte
name|ch
init|=
name|bytes
index|[
name|i
index|]
decl_stmt|;
comment|// remove any characters outside the valid UTF-8 range as well as all control characters
comment|// except tabs and new lines
if|if
condition|(
operator|!
operator|(
operator|(
name|ch
operator|>
literal|31
operator|&&
name|ch
operator|<
literal|253
operator|)
operator|||
name|ch
operator|==
literal|'\t'
operator|||
name|ch
operator|==
literal|'\n'
operator|||
name|ch
operator|==
literal|'\r'
operator|)
condition|)
block|{
name|bytes
index|[
name|i
index|]
operator|=
literal|' '
expr_stmt|;
block|}
block|}
return|return
operator|new
name|String
argument_list|(
name|bytes
argument_list|,
name|UTF8
argument_list|)
return|;
block|}
comment|/**      * The default language      * @return the defaultLang      */
specifier|public
name|String
name|getDefaultLanguage
parameter_list|()
block|{
return|return
name|defaultLang
return|;
block|}
comment|/**      * Checks if the parsed language is enabled for processing.      * If<code>null</code> is parsed as language this returns<code>false</code>      * even if processing of all languages is enabled.<p>      * NOTE: If this Method returns<code>true</code> this does      * not mean that text with this language can be actually processed because this      * also requires that the NER model for this language are available via the      * parsed {@link OpenNLP} instance.      * @param lang the language      * @return the state      */
specifier|public
name|boolean
name|isProcessedLangage
parameter_list|(
name|String
name|lang
parameter_list|)
block|{
return|return
name|lang
operator|!=
literal|null
operator|&&
operator|(
name|processedLangs
operator|.
name|isEmpty
argument_list|()
operator|||
name|processedLangs
operator|.
name|contains
argument_list|(
name|lang
argument_list|)
operator|)
return|;
block|}
comment|/*      * The following Utility extracts the language from the metadata of the      * parsed Content Item.      * This Utility is actually a copy of the same form the KeywordExtractionEngine.      * TODO: change this to a global Utility as soon as STANBOL Enhancement      * Structure is defined      */
comment|/**      * The literal representing the LangIDEngine as creator.      */
specifier|public
specifier|static
specifier|final
name|Literal
name|LANG_ID_ENGINE_NAME
init|=
name|LiteralFactory
operator|.
name|getInstance
argument_list|()
operator|.
name|createTypedLiteral
argument_list|(
literal|"org.apache.stanbol.enhancer.engines.langid.LangIdEnhancementEngine"
argument_list|)
decl_stmt|;
comment|/**      * Extracts the language of the parsed ContentItem by using      * {@link EnhancementEngineHelper#getLanguage(ContentItem)} and       * {@link #defaultLang} as default      * @param ci the content item      * @return the language      */
specifier|private
name|String
name|extractLanguage
parameter_list|(
name|ContentItem
name|ci
parameter_list|)
block|{
name|String
name|lang
init|=
name|EnhancementEngineHelper
operator|.
name|getLanguage
argument_list|(
name|ci
argument_list|)
decl_stmt|;
comment|//        MGraph metadata = ci.getMetadata();
comment|//        Iterator<Triple> langaugeEnhancementCreatorTriples =
comment|//            metadata.filter(null, Properties.DC_CREATOR, LANG_ID_ENGINE_NAME);
comment|//        if(langaugeEnhancementCreatorTriples.hasNext()){
comment|//            String lang = EnhancementEngineHelper.getString(metadata,
comment|//                langaugeEnhancementCreatorTriples.next().getSubject(),
comment|//                Properties.DC_LANGUAGE);
if|if
condition|(
name|lang
operator|!=
literal|null
condition|)
block|{
return|return
name|lang
return|;
block|}
else|else
block|{
name|log
operator|.
name|info
argument_list|(
literal|"Unable to extract language for ContentItem %s! The Enhancement of the %s is missing the %s property"
argument_list|,
operator|new
name|Object
index|[]
block|{
name|ci
operator|.
name|getUri
argument_list|()
operator|.
name|getUnicodeString
argument_list|()
block|,
name|LANG_ID_ENGINE_NAME
operator|.
name|getLexicalForm
argument_list|()
block|,
name|Properties
operator|.
name|DC_LANGUAGE
block|}
argument_list|)
expr_stmt|;
name|log
operator|.
name|info
argument_list|(
literal|" ... return '{}' as default"
argument_list|,
name|defaultLang
argument_list|)
expr_stmt|;
return|return
name|defaultLang
return|;
block|}
comment|//        } else {
comment|//            log.info("Unable to extract language for ContentItem {}! Is the {} active?",
comment|//                ci.getUri().getUnicodeString(),LANG_ID_ENGINE_NAME.getLexicalForm());
comment|//            log.info(" ... return '{}' as default",defaultLang);
comment|//            return defaultLang;
comment|//        }
block|}
block|}
end_class

end_unit

