begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|cmsadapter
operator|.
name|servicesapi
operator|.
name|mapping
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|cmsadapter
operator|.
name|servicesapi
operator|.
name|model
operator|.
name|web
operator|.
name|CMSObject
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|cmsadapter
operator|.
name|servicesapi
operator|.
name|model
operator|.
name|web
operator|.
name|ObjectTypeDefinition
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|cmsadapter
operator|.
name|servicesapi
operator|.
name|model
operator|.
name|web
operator|.
name|PropertyDefinition
import|;
end_import

begin_import
import|import
name|com
operator|.
name|hp
operator|.
name|hpl
operator|.
name|jena
operator|.
name|rdf
operator|.
name|model
operator|.
name|RDFList
import|;
end_import

begin_comment
comment|/**  * Represents how different type of OWL entities are named in an extraction context.  *   * @author Suat  *   */
end_comment

begin_interface
specifier|public
interface|interface
name|NamingStrategy
block|{
name|String
name|getClassName
parameter_list|(
name|String
name|ontologyURI
parameter_list|,
name|CMSObject
name|cmsObject
parameter_list|)
function_decl|;
name|String
name|getClassName
parameter_list|(
name|String
name|ontologyURI
parameter_list|,
name|ObjectTypeDefinition
name|objectTypeDefinition
parameter_list|)
function_decl|;
name|String
name|getClassName
parameter_list|(
name|String
name|ontologyURI
parameter_list|,
name|String
name|reference
parameter_list|)
function_decl|;
name|String
name|getIndividualName
parameter_list|(
name|String
name|ontologyURI
parameter_list|,
name|CMSObject
name|cmsObject
parameter_list|)
function_decl|;
name|String
name|getIndividualName
parameter_list|(
name|String
name|ontologyURI
parameter_list|,
name|String
name|reference
parameter_list|)
function_decl|;
name|String
name|getPropertyName
parameter_list|(
name|String
name|ontologyURI
parameter_list|,
name|String
name|reference
parameter_list|)
function_decl|;
name|String
name|getObjectPropertyName
parameter_list|(
name|String
name|ontologyURI
parameter_list|,
name|String
name|reference
parameter_list|)
function_decl|;
name|String
name|getObjectPropertyName
parameter_list|(
name|String
name|ontologyURI
parameter_list|,
name|PropertyDefinition
name|propertyDefinition
parameter_list|)
function_decl|;
name|String
name|getDataPropertyName
parameter_list|(
name|String
name|ontologyURI
parameter_list|,
name|String
name|reference
parameter_list|)
function_decl|;
name|String
name|getDataPropertyName
parameter_list|(
name|String
name|ontologyURI
parameter_list|,
name|PropertyDefinition
name|propertyDefinition
parameter_list|)
function_decl|;
name|String
name|getUnionClassURI
parameter_list|(
name|String
name|ontologyURI
parameter_list|,
name|RDFList
name|list
parameter_list|)
function_decl|;
block|}
end_interface

end_unit

