begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|commons
operator|.
name|solr
operator|.
name|install
operator|.
name|impl
package|;
end_package

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|commons
operator|.
name|solr
operator|.
name|managed
operator|.
name|ManagedIndexConstants
operator|.
name|INDEX_NAME
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Map
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|sling
operator|.
name|installer
operator|.
name|api
operator|.
name|tasks
operator|.
name|InstallTask
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|sling
operator|.
name|installer
operator|.
name|api
operator|.
name|tasks
operator|.
name|InstallationContext
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|sling
operator|.
name|installer
operator|.
name|api
operator|.
name|tasks
operator|.
name|ResourceState
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|sling
operator|.
name|installer
operator|.
name|api
operator|.
name|tasks
operator|.
name|TaskResourceGroup
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|commons
operator|.
name|solr
operator|.
name|managed
operator|.
name|ManagedIndexConstants
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|commons
operator|.
name|solr
operator|.
name|managed
operator|.
name|ManagedSolrServer
import|;
end_import

begin_import
import|import
name|org
operator|.
name|slf4j
operator|.
name|Logger
import|;
end_import

begin_import
import|import
name|org
operator|.
name|slf4j
operator|.
name|LoggerFactory
import|;
end_import

begin_comment
comment|/**  * TODO: To remove a SolrIndex one would need first to close the SolrCore or shutdown the SolrContainer. This  * is currently not possible be cause the current architecture was not intended to support that.  *<p>  * To implement this one would need access to the CoreContainer with the core running on top of the Core to  * remove. Than one would need to call {@link CoreContainer#remove(String)} with the core and  * {@link CoreContainer#persist()} to remove the core also from the solr.xml. After that one can remove the  * files from the disk.  *<p>  * This would still have the problem that other components using an {@link EmbeddedSolrServer} that is based  * on this core would not be notified about such a change.  *   * @author Rupert Westenthaler  *   */
end_comment

begin_class
specifier|public
class|class
name|IndexRemoveTask
extends|extends
name|InstallTask
block|{
specifier|private
specifier|static
specifier|final
name|Logger
name|log
init|=
name|LoggerFactory
operator|.
name|getLogger
argument_list|(
name|IndexRemoveTask
operator|.
name|class
argument_list|)
decl_stmt|;
comment|/**      * Use 11 because the RemoveConfiguration uses 10 and we need to ensure that the files are removed after      * the services are shut down.      */
specifier|private
specifier|static
specifier|final
name|String
name|CONFIG_INSTALL_ORDER
init|=
literal|"11-"
decl_stmt|;
comment|/**      * Mapping for the managed servers. The default server uses the<code>null</code>      * key!      */
specifier|private
specifier|final
name|Map
argument_list|<
name|String
argument_list|,
name|ManagedSolrServer
argument_list|>
name|managedServers
decl_stmt|;
specifier|public
name|IndexRemoveTask
parameter_list|(
name|TaskResourceGroup
name|trg
parameter_list|,
name|Map
argument_list|<
name|String
argument_list|,
name|ManagedSolrServer
argument_list|>
name|managedServers
parameter_list|)
block|{
name|super
argument_list|(
name|trg
argument_list|)
expr_stmt|;
if|if
condition|(
name|managedServers
operator|==
literal|null
condition|)
block|{
throw|throw
operator|new
name|IllegalArgumentException
argument_list|(
literal|"The parsed map with the ManagedSolrServer MUST NOT be NULL!"
argument_list|)
throw|;
block|}
name|this
operator|.
name|managedServers
operator|=
name|managedServers
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|execute
parameter_list|(
name|InstallationContext
name|ctx
parameter_list|)
block|{
name|String
name|indexName
init|=
operator|(
name|String
operator|)
name|getResource
argument_list|()
operator|.
name|getAttribute
argument_list|(
name|INDEX_NAME
argument_list|)
decl_stmt|;
if|if
condition|(
name|indexName
operator|==
literal|null
condition|)
block|{
name|log
operator|.
name|error
argument_list|(
literal|"Unable to remove Managed Index because the required Property '{}'"
operator|+
literal|"used to define the name of the Index is missing"
argument_list|,
name|INDEX_NAME
argument_list|)
expr_stmt|;
name|setFinishedState
argument_list|(
name|ResourceState
operator|.
name|IGNORED
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|String
name|serverName
init|=
operator|(
name|String
operator|)
name|getResource
argument_list|()
operator|.
name|getAttribute
argument_list|(
name|ManagedIndexConstants
operator|.
name|SERVER_NAME
argument_list|)
decl_stmt|;
name|ManagedSolrServer
name|server
init|=
name|managedServers
operator|.
name|get
argument_list|(
name|serverName
argument_list|)
decl_stmt|;
if|if
condition|(
name|server
operator|==
literal|null
condition|)
block|{
name|log
operator|.
name|warn
argument_list|(
literal|"Unable to remove Managed Solr Index {} because the {} "
operator|+
literal|"Server {} is currently not active!"
argument_list|,
operator|new
name|Object
index|[]
block|{
name|indexName
block|,
name|serverName
operator|==
literal|null
condition|?
literal|"default"
else|:
literal|""
block|,
name|serverName
operator|!=
literal|null
condition|?
name|serverName
else|:
literal|""
block|}
argument_list|)
expr_stmt|;
name|setFinishedState
argument_list|(
name|ResourceState
operator|.
name|IGNORED
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|server
operator|.
name|removeIndex
argument_list|(
name|indexName
argument_list|,
literal|true
argument_list|)
expr_stmt|;
name|setFinishedState
argument_list|(
name|ResourceState
operator|.
name|UNINSTALLED
argument_list|)
expr_stmt|;
block|}
block|}
block|}
annotation|@
name|Override
specifier|public
name|String
name|getSortKey
parameter_list|()
block|{
return|return
name|CONFIG_INSTALL_ORDER
operator|+
name|getResource
argument_list|()
operator|.
name|getEntityId
argument_list|()
return|;
block|}
block|}
end_class

end_unit

