begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|cmsadapter
operator|.
name|core
operator|.
name|decorated
package|;
end_package

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|cmsadapter
operator|.
name|core
operator|.
name|decorated
operator|.
name|NamingHelper
operator|.
name|LOCAL_NAME
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|cmsadapter
operator|.
name|servicesapi
operator|.
name|model
operator|.
name|web
operator|.
name|CMSObject
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|cmsadapter
operator|.
name|servicesapi
operator|.
name|model
operator|.
name|web
operator|.
name|ObjectFactory
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|cmsadapter
operator|.
name|servicesapi
operator|.
name|model
operator|.
name|web
operator|.
name|Property
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|cmsadapter
operator|.
name|servicesapi
operator|.
name|model
operator|.
name|web
operator|.
name|PropertyDefinition
import|;
end_import

begin_class
specifier|public
class|class
name|PropertyBuilder
block|{
specifier|private
specifier|static
name|ObjectFactory
name|of
init|=
operator|new
name|ObjectFactory
argument_list|()
decl_stmt|;
specifier|private
name|Property
name|instance
init|=
name|of
operator|.
name|createProperty
argument_list|()
decl_stmt|;
specifier|public
name|PropertyBuilder
parameter_list|(
name|String
name|prefix
parameter_list|)
block|{
name|instance
operator|.
name|setLocalname
argument_list|(
name|prefix
operator|+
name|LOCAL_NAME
argument_list|)
expr_stmt|;
block|}
specifier|public
name|PropertyBuilder
name|propertyDefinition
parameter_list|(
name|PropertyDefinition
name|propDef
parameter_list|)
block|{
name|instance
operator|.
name|setPropertyDefinition
argument_list|(
name|propDef
argument_list|)
expr_stmt|;
return|return
name|this
return|;
block|}
specifier|public
name|PropertyBuilder
name|containerObjectRef
parameter_list|(
name|CMSObject
name|obj
parameter_list|)
block|{
name|instance
operator|.
name|setContainerObjectRef
argument_list|(
name|obj
operator|.
name|getUniqueRef
argument_list|()
argument_list|)
expr_stmt|;
return|return
name|this
return|;
block|}
specifier|public
name|Property
name|build
parameter_list|()
block|{
return|return
name|instance
return|;
block|}
block|}
end_class

end_unit

