begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/* * Licensed to the Apache Software Foundation (ASF) under one or more * contributor license agreements.  See the NOTICE file distributed with * this work for additional information regarding copyright ownership. * The ASF licenses this file to You under the Apache License, Version 2.0 * (the "License"); you may not use this file except in compliance with * the License.  You may obtain a copy of the License at * *     http://www.apache.org/licenses/LICENSE-2.0 * * Unless required by applicable law or agreed to in writing, software * distributed under the License is distributed on an "AS IS" BASIS, * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. * See the License for the specific language governing permissions and * limitations under the License. */
end_comment

begin_comment
comment|//
end_comment

begin_comment
comment|// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.4-b02-fcs
end_comment

begin_comment
comment|// See<a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
end_comment

begin_comment
comment|// Any modifications to this file will be lost upon recompilation of the source schema.
end_comment

begin_comment
comment|// Generated on: 2009.05.13 at 09:50:16 AM EEST
end_comment

begin_comment
comment|//
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|ontologymanager
operator|.
name|store
operator|.
name|model
package|;
end_package

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|bind
operator|.
name|annotation
operator|.
name|XmlAccessType
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|bind
operator|.
name|annotation
operator|.
name|XmlAccessorType
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|bind
operator|.
name|annotation
operator|.
name|XmlElement
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|bind
operator|.
name|annotation
operator|.
name|XmlRootElement
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|bind
operator|.
name|annotation
operator|.
name|XmlType
import|;
end_import

begin_comment
comment|/**  *<p>  * Java class for anonymous complex type.  *   *<p>  * The following schema fragment specifies the expected content contained within this class.  *   *<pre>  *&lt;complexType>  *&lt;complexContent>  *&lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">  *&lt;sequence>  *&lt;element ref="{model.rest.persistence.iks.srdc.com.tr}IndividualMetaInformation"/>  *&lt;element ref="{model.rest.persistence.iks.srdc.com.tr}ContainerClasses"/>  *&lt;element ref="{model.rest.persistence.iks.srdc.com.tr}PropertyAssertions"/>  *&lt;/sequence>  *&lt;/restriction>  *&lt;/complexContent>  *&lt;/complexType>  *</pre>  *   *   */
end_comment

begin_class
annotation|@
name|XmlAccessorType
argument_list|(
name|XmlAccessType
operator|.
name|FIELD
argument_list|)
annotation|@
name|XmlType
argument_list|(
name|name
operator|=
literal|""
argument_list|,
name|propOrder
operator|=
block|{
literal|"individualMetaInformation"
block|,
literal|"containerClasses"
block|,
literal|"propertyAssertions"
block|}
argument_list|)
annotation|@
name|XmlRootElement
argument_list|(
name|name
operator|=
literal|"IndividualContext"
argument_list|)
specifier|public
class|class
name|IndividualContext
block|{
annotation|@
name|XmlElement
argument_list|(
name|name
operator|=
literal|"IndividualMetaInformation"
argument_list|,
name|required
operator|=
literal|true
argument_list|)
specifier|protected
name|IndividualMetaInformation
name|individualMetaInformation
decl_stmt|;
annotation|@
name|XmlElement
argument_list|(
name|name
operator|=
literal|"ContainerClasses"
argument_list|,
name|required
operator|=
literal|true
argument_list|)
specifier|protected
name|ContainerClasses
name|containerClasses
decl_stmt|;
annotation|@
name|XmlElement
argument_list|(
name|name
operator|=
literal|"PropertyAssertions"
argument_list|,
name|required
operator|=
literal|true
argument_list|)
specifier|protected
name|PropertyAssertions
name|propertyAssertions
decl_stmt|;
comment|/**      * Gets the value of the individualMetaInformation property.      *       * @return possible object is {@link IndividualMetaInformation }      *       */
specifier|public
name|IndividualMetaInformation
name|getIndividualMetaInformation
parameter_list|()
block|{
return|return
name|individualMetaInformation
return|;
block|}
comment|/**      * Sets the value of the individualMetaInformation property.      *       * @param value      *            allowed object is {@link IndividualMetaInformation }      *       */
specifier|public
name|void
name|setIndividualMetaInformation
parameter_list|(
name|IndividualMetaInformation
name|value
parameter_list|)
block|{
name|this
operator|.
name|individualMetaInformation
operator|=
name|value
expr_stmt|;
block|}
comment|/**      * Gets the value of the containerClasses property.      *       * @return possible object is {@link ContainerClasses }      *       */
specifier|public
name|ContainerClasses
name|getContainerClasses
parameter_list|()
block|{
return|return
name|containerClasses
return|;
block|}
comment|/**      * Sets the value of the containerClasses property.      *       * @param value      *            allowed object is {@link ContainerClasses }      *       */
specifier|public
name|void
name|setContainerClasses
parameter_list|(
name|ContainerClasses
name|value
parameter_list|)
block|{
name|this
operator|.
name|containerClasses
operator|=
name|value
expr_stmt|;
block|}
comment|/**      * Gets the value of the propertyAssertions property.      *       * @return possible object is {@link PropertyAssertions }      *       */
specifier|public
name|PropertyAssertions
name|getPropertyAssertions
parameter_list|()
block|{
return|return
name|propertyAssertions
return|;
block|}
comment|/**      * Sets the value of the propertyAssertions property.      *       * @param value      *            allowed object is {@link PropertyAssertions }      *       */
specifier|public
name|void
name|setPropertyAssertions
parameter_list|(
name|PropertyAssertions
name|value
parameter_list|)
block|{
name|this
operator|.
name|propertyAssertions
operator|=
name|value
expr_stmt|;
block|}
block|}
end_class

end_unit

