begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/* * Licensed to the Apache Software Foundation (ASF) under one or more * contributor license agreements.  See the NOTICE file distributed with * this work for additional information regarding copyright ownership. * The ASF licenses this file to You under the Apache License, Version 2.0 * (the "License"); you may not use this file except in compliance with * the License.  You may obtain a copy of the License at * *     http://www.apache.org/licenses/LICENSE-2.0 * * Unless required by applicable law or agreed to in writing, software * distributed under the License is distributed on an "AS IS" BASIS, * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. * See the License for the specific language governing permissions and * limitations under the License. */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|engines
operator|.
name|tika
operator|.
name|handler
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|Writer
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tika
operator|.
name|sax
operator|.
name|ToTextContentHandler
import|;
end_import

begin_import
import|import
name|org
operator|.
name|xml
operator|.
name|sax
operator|.
name|Attributes
import|;
end_import

begin_import
import|import
name|org
operator|.
name|xml
operator|.
name|sax
operator|.
name|SAXException
import|;
end_import

begin_comment
comment|/**  * Small extensions to the default {@link ToTextContentHandler}. This allows  * to<ul>  *<li>skip ignoreable whitespaces  *<li>skip linebreaks within literals  *</ul>  *   * @author Rupert Westenthaler  *  */
end_comment

begin_class
specifier|public
class|class
name|PlainTextHandler
extends|extends
name|ToTextContentHandler
block|{
specifier|private
specifier|final
name|boolean
name|skipWhitespaces
decl_stmt|;
specifier|private
specifier|final
name|boolean
name|skipLinebreakes
decl_stmt|;
specifier|public
name|PlainTextHandler
parameter_list|(
name|Writer
name|writer
parameter_list|,
name|boolean
name|skipIgnoreableWhitespaces
parameter_list|,
name|boolean
name|skipLinebreaksWithinLiterals
parameter_list|)
block|{
name|super
argument_list|(
name|writer
argument_list|)
expr_stmt|;
name|this
operator|.
name|skipWhitespaces
operator|=
name|skipIgnoreableWhitespaces
expr_stmt|;
name|this
operator|.
name|skipLinebreakes
operator|=
name|skipLinebreaksWithinLiterals
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|ignorableWhitespace
parameter_list|(
name|char
index|[]
name|ch
parameter_list|,
name|int
name|start
parameter_list|,
name|int
name|length
parameter_list|)
throws|throws
name|SAXException
block|{
if|if
condition|(
operator|!
name|skipWhitespaces
condition|)
block|{
name|super
operator|.
name|ignorableWhitespace
argument_list|(
name|ch
argument_list|,
name|start
argument_list|,
name|length
argument_list|)
expr_stmt|;
block|}
comment|//else ignore
block|}
annotation|@
name|Override
specifier|public
name|void
name|characters
parameter_list|(
name|char
index|[]
name|ch
parameter_list|,
name|int
name|start
parameter_list|,
name|int
name|length
parameter_list|)
throws|throws
name|SAXException
block|{
name|int
name|in
decl_stmt|;
if|if
condition|(
name|skipLinebreakes
condition|)
block|{
comment|//use an in(serte) and an it(erator) index to avoid copying
comment|//the data to a new char[].
name|in
operator|=
name|start
expr_stmt|;
for|for
control|(
name|int
name|it
init|=
name|start
init|;
name|it
operator|<
name|length
condition|;
name|it
operator|++
control|)
block|{
if|if
condition|(
name|ch
index|[
name|it
index|]
operator|!=
literal|'\n'
condition|)
block|{
name|ch
index|[
name|in
index|]
operator|=
name|ch
index|[
name|it
index|]
expr_stmt|;
name|in
operator|++
expr_stmt|;
block|}
comment|//ignore line breaks
block|}
if|if
condition|(
name|in
operator|==
name|start
condition|)
block|{
comment|//only line breaks
return|return;
comment|// -> nothing to add
block|}
block|}
else|else
block|{
name|in
operator|=
name|length
expr_stmt|;
block|}
name|super
operator|.
name|characters
argument_list|(
name|ch
argument_list|,
name|start
argument_list|,
name|in
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|startElement
parameter_list|(
name|String
name|uri
parameter_list|,
name|String
name|localName
parameter_list|,
name|String
name|qName
parameter_list|,
name|Attributes
name|attributes
parameter_list|)
throws|throws
name|SAXException
block|{
name|super
operator|.
name|startElement
argument_list|(
name|uri
argument_list|,
name|localName
argument_list|,
name|qName
argument_list|,
name|attributes
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|endElement
parameter_list|(
name|String
name|uri
parameter_list|,
name|String
name|localName
parameter_list|,
name|String
name|qName
parameter_list|)
throws|throws
name|SAXException
block|{
comment|// TODO Auto-generated method stub
name|super
operator|.
name|endElement
argument_list|(
name|uri
argument_list|,
name|localName
argument_list|,
name|qName
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

