begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|rules
operator|.
name|manager
operator|.
name|atoms
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|rules
operator|.
name|base
operator|.
name|api
operator|.
name|URIResource
import|;
end_import

begin_class
specifier|public
class|class
name|TypedLiteralAtom
extends|extends
name|ExpressionAtom
block|{
specifier|private
name|ExpressionAtom
name|value
decl_stmt|;
specifier|private
name|URIResource
name|xsdType
decl_stmt|;
specifier|public
name|TypedLiteralAtom
parameter_list|(
name|ExpressionAtom
name|value
parameter_list|,
name|URIResource
name|xsdType
parameter_list|)
block|{
name|this
operator|.
name|value
operator|=
name|value
expr_stmt|;
name|this
operator|.
name|xsdType
operator|=
name|xsdType
expr_stmt|;
block|}
specifier|public
name|ExpressionAtom
name|getValue
parameter_list|()
block|{
return|return
name|value
return|;
block|}
specifier|public
name|URIResource
name|getXsdType
parameter_list|()
block|{
return|return
name|xsdType
return|;
block|}
annotation|@
name|Override
specifier|public
name|String
name|toString
parameter_list|()
block|{
if|if
condition|(
name|xsdType
operator|!=
literal|null
condition|)
block|{
return|return
name|value
operator|.
name|toString
argument_list|()
operator|+
literal|"^^"
operator|+
name|xsdType
operator|.
name|toString
argument_list|()
return|;
block|}
else|else
block|{
return|return
name|value
operator|.
name|toString
argument_list|()
return|;
block|}
block|}
annotation|@
name|Override
specifier|public
name|String
name|prettyPrint
parameter_list|()
block|{
if|if
condition|(
name|xsdType
operator|!=
literal|null
condition|)
block|{
return|return
name|value
operator|+
literal|" with type "
operator|+
name|xsdType
operator|.
name|toString
argument_list|()
return|;
block|}
else|else
block|{
return|return
name|value
operator|.
name|toString
argument_list|()
return|;
block|}
block|}
block|}
end_class

end_unit

