begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|rules
operator|.
name|manager
operator|.
name|atoms
package|;
end_package

begin_import
import|import
name|java
operator|.
name|net
operator|.
name|URI
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|rules
operator|.
name|base
operator|.
name|api
operator|.
name|Symbols
import|;
end_import

begin_class
specifier|public
class|class
name|VariableAtom
extends|extends
name|IObjectAtom
block|{
specifier|private
name|URI
name|uri
decl_stmt|;
specifier|private
name|boolean
name|negative
decl_stmt|;
specifier|public
name|VariableAtom
parameter_list|(
name|URI
name|uri
parameter_list|,
name|boolean
name|negative
parameter_list|)
block|{
name|this
operator|.
name|uri
operator|=
name|uri
expr_stmt|;
name|this
operator|.
name|negative
operator|=
name|negative
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|URI
name|getURI
parameter_list|()
block|{
return|return
name|uri
return|;
block|}
specifier|public
name|boolean
name|isNegative
parameter_list|()
block|{
return|return
name|negative
return|;
block|}
annotation|@
name|Override
specifier|public
name|String
name|toString
parameter_list|()
block|{
return|return
literal|"?"
operator|+
name|getVariableName
argument_list|()
return|;
block|}
annotation|@
name|Override
specifier|public
name|String
name|prettyPrint
parameter_list|()
block|{
return|return
literal|"variable "
operator|+
name|uri
operator|.
name|toString
argument_list|()
return|;
block|}
specifier|public
name|String
name|getVariableName
parameter_list|()
block|{
name|String
name|uriString
init|=
name|uri
operator|.
name|toString
argument_list|()
decl_stmt|;
name|uriString
operator|=
name|uriString
operator|.
name|replace
argument_list|(
name|Symbols
operator|.
name|variablesPrefix
argument_list|,
literal|""
argument_list|)
expr_stmt|;
return|return
name|uriString
return|;
block|}
block|}
end_class

end_unit

