begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|entityhub
operator|.
name|jersey
operator|.
name|writers
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|commons
operator|.
name|namespaceprefix
operator|.
name|NamespacePrefixService
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|entityhub
operator|.
name|servicesapi
operator|.
name|model
operator|.
name|Entity
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|entityhub
operator|.
name|servicesapi
operator|.
name|model
operator|.
name|Representation
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|entityhub
operator|.
name|servicesapi
operator|.
name|query
operator|.
name|QueryResultList
import|;
end_import

begin_import
import|import
name|org
operator|.
name|codehaus
operator|.
name|jettison
operator|.
name|json
operator|.
name|JSONArray
import|;
end_import

begin_import
import|import
name|org
operator|.
name|codehaus
operator|.
name|jettison
operator|.
name|json
operator|.
name|JSONException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|codehaus
operator|.
name|jettison
operator|.
name|json
operator|.
name|JSONObject
import|;
end_import

begin_class
specifier|final
class|class
name|QueryResultsToJSON
block|{
specifier|private
name|QueryResultsToJSON
parameter_list|()
block|{
comment|/* do not create instances of utility classes */
block|}
specifier|static
parameter_list|<
name|T
parameter_list|>
name|JSONObject
name|toJSON
parameter_list|(
name|QueryResultList
argument_list|<
name|?
argument_list|>
name|resultList
parameter_list|,
name|NamespacePrefixService
name|nsPrefixService
parameter_list|)
throws|throws
name|JSONException
block|{
name|JSONObject
name|jResultList
init|=
operator|new
name|JSONObject
argument_list|()
decl_stmt|;
if|if
condition|(
name|resultList
operator|.
name|getQuery
argument_list|()
operator|!=
literal|null
condition|)
block|{
name|jResultList
operator|.
name|put
argument_list|(
literal|"query"
argument_list|,
name|FieldQueryToJSON
operator|.
name|toJSON
argument_list|(
name|resultList
operator|.
name|getQuery
argument_list|()
argument_list|,
name|nsPrefixService
argument_list|)
argument_list|)
expr_stmt|;
block|}
name|jResultList
operator|.
name|put
argument_list|(
literal|"results"
argument_list|,
name|convertResultsToJSON
argument_list|(
name|resultList
argument_list|,
name|resultList
operator|.
name|getType
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
return|return
name|jResultList
return|;
block|}
specifier|private
specifier|static
parameter_list|<
name|T
parameter_list|>
name|JSONArray
name|convertResultsToJSON
parameter_list|(
name|Iterable
argument_list|<
name|?
argument_list|>
name|results
parameter_list|,
name|Class
argument_list|<
name|?
argument_list|>
name|type
parameter_list|)
throws|throws
name|JSONException
block|{
name|JSONArray
name|jResults
init|=
operator|new
name|JSONArray
argument_list|()
decl_stmt|;
if|if
condition|(
name|String
operator|.
name|class
operator|.
name|isAssignableFrom
argument_list|(
name|type
argument_list|)
condition|)
block|{
for|for
control|(
name|Object
name|result
range|:
name|results
control|)
block|{
name|jResults
operator|.
name|put
argument_list|(
name|result
argument_list|)
expr_stmt|;
block|}
block|}
elseif|else
if|if
condition|(
name|Representation
operator|.
name|class
operator|.
name|isAssignableFrom
argument_list|(
name|type
argument_list|)
condition|)
block|{
for|for
control|(
name|Object
name|result
range|:
name|results
control|)
block|{
name|jResults
operator|.
name|put
argument_list|(
name|EntityToJSON
operator|.
name|toJSON
argument_list|(
operator|(
name|Representation
operator|)
name|result
argument_list|)
argument_list|)
expr_stmt|;
block|}
block|}
elseif|else
if|if
condition|(
name|Entity
operator|.
name|class
operator|.
name|isAssignableFrom
argument_list|(
name|type
argument_list|)
condition|)
block|{
for|for
control|(
name|Object
name|result
range|:
name|results
control|)
block|{
name|jResults
operator|.
name|put
argument_list|(
name|EntityToJSON
operator|.
name|toJSON
argument_list|(
operator|(
name|Entity
operator|)
name|result
argument_list|)
argument_list|)
expr_stmt|;
block|}
block|}
return|return
name|jResults
return|;
block|}
block|}
end_class

end_unit

