begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|contenthub
operator|.
name|core
operator|.
name|search
operator|.
name|execution
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Collections
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|HashSet
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Set
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|contenthub
operator|.
name|servicesapi
operator|.
name|search
operator|.
name|execution
operator|.
name|ClassResource
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|contenthub
operator|.
name|servicesapi
operator|.
name|search
operator|.
name|execution
operator|.
name|DocumentResource
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|contenthub
operator|.
name|servicesapi
operator|.
name|search
operator|.
name|execution
operator|.
name|ExternalResource
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|contenthub
operator|.
name|servicesapi
operator|.
name|search
operator|.
name|execution
operator|.
name|IndividualResource
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|contenthub
operator|.
name|servicesapi
operator|.
name|search
operator|.
name|execution
operator|.
name|Keyword
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|contenthub
operator|.
name|servicesapi
operator|.
name|search
operator|.
name|vocabulary
operator|.
name|SearchVocabulary
import|;
end_import

begin_import
import|import
name|com
operator|.
name|hp
operator|.
name|hpl
operator|.
name|jena
operator|.
name|enhanced
operator|.
name|EnhGraph
import|;
end_import

begin_import
import|import
name|com
operator|.
name|hp
operator|.
name|hpl
operator|.
name|jena
operator|.
name|graph
operator|.
name|Node
import|;
end_import

begin_import
import|import
name|com
operator|.
name|hp
operator|.
name|hpl
operator|.
name|jena
operator|.
name|rdf
operator|.
name|model
operator|.
name|RDFNode
import|;
end_import

begin_import
import|import
name|com
operator|.
name|hp
operator|.
name|hpl
operator|.
name|jena
operator|.
name|rdf
operator|.
name|model
operator|.
name|Statement
import|;
end_import

begin_import
import|import
name|com
operator|.
name|hp
operator|.
name|hpl
operator|.
name|jena
operator|.
name|vocabulary
operator|.
name|RDF
import|;
end_import

begin_comment
comment|/**  * Implementation of {@link ExternalResource}.  *   * @author cihan  *   */
end_comment

begin_class
specifier|public
class|class
name|ExternalResourceImpl
extends|extends
name|AbstractKeywordRelatedResource
implements|implements
name|ExternalResource
block|{
name|ExternalResourceImpl
parameter_list|(
name|Node
name|n
parameter_list|,
name|EnhGraph
name|g
parameter_list|,
name|Double
name|weight
parameter_list|,
name|Double
name|score
parameter_list|,
name|String
name|externalEntity
parameter_list|,
name|Keyword
name|related
parameter_list|,
name|SearchContextFactoryImpl
name|factory
parameter_list|)
block|{
name|super
argument_list|(
name|n
argument_list|,
name|g
argument_list|,
name|weight
argument_list|,
name|score
argument_list|,
name|related
argument_list|,
name|factory
argument_list|)
expr_stmt|;
name|this
operator|.
name|addProperty
argument_list|(
name|RDF
operator|.
name|type
argument_list|,
name|SearchVocabulary
operator|.
name|EXTERNAL_RESOURCE
argument_list|)
expr_stmt|;
name|this
operator|.
name|addProperty
argument_list|(
name|SearchVocabulary
operator|.
name|EXTERNAL_ENTITY
argument_list|,
name|this
operator|.
name|getModel
argument_list|()
operator|.
name|createResource
argument_list|(
name|externalEntity
argument_list|)
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|addType
parameter_list|(
name|String
name|type
parameter_list|)
block|{
name|this
operator|.
name|getPropertyResourceValue
argument_list|(
name|SearchVocabulary
operator|.
name|EXTERNAL_ENTITY
argument_list|)
operator|.
name|addProperty
argument_list|(
name|RDF
operator|.
name|type
argument_list|,
name|this
operator|.
name|getModel
argument_list|()
operator|.
name|createResource
argument_list|(
name|type
argument_list|)
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|String
name|getReference
parameter_list|()
block|{
return|return
name|this
operator|.
name|getPropertyResourceValue
argument_list|(
name|SearchVocabulary
operator|.
name|EXTERNAL_ENTITY
argument_list|)
operator|.
name|getURI
argument_list|()
return|;
block|}
annotation|@
name|Override
specifier|public
name|Set
argument_list|<
name|String
argument_list|>
name|getTypes
parameter_list|()
block|{
name|Set
argument_list|<
name|Statement
argument_list|>
name|typeSet
init|=
name|this
operator|.
name|getPropertyResourceValue
argument_list|(
name|SearchVocabulary
operator|.
name|EXTERNAL_ENTITY
argument_list|)
operator|.
name|listProperties
argument_list|(
name|RDF
operator|.
name|type
argument_list|)
operator|.
name|toSet
argument_list|()
decl_stmt|;
name|Set
argument_list|<
name|String
argument_list|>
name|types
init|=
operator|new
name|HashSet
argument_list|<
name|String
argument_list|>
argument_list|(
name|typeSet
operator|.
name|size
argument_list|()
argument_list|)
decl_stmt|;
for|for
control|(
name|Statement
name|stmt
range|:
name|typeSet
control|)
block|{
name|types
operator|.
name|add
argument_list|(
name|stmt
operator|.
name|getObject
argument_list|()
operator|.
name|asResource
argument_list|()
operator|.
name|getURI
argument_list|()
argument_list|)
expr_stmt|;
block|}
return|return
name|types
return|;
block|}
annotation|@
name|Override
specifier|public
name|Set
argument_list|<
name|DocumentResource
argument_list|>
name|getRelatedDocuments
parameter_list|()
block|{
name|Set
argument_list|<
name|DocumentResource
argument_list|>
name|docs
init|=
operator|new
name|HashSet
argument_list|<
name|DocumentResource
argument_list|>
argument_list|()
decl_stmt|;
for|for
control|(
name|RDFNode
name|res
range|:
name|this
operator|.
name|listPropertyValues
argument_list|(
name|SearchVocabulary
operator|.
name|RELATED_DOCUMENT
argument_list|)
operator|.
name|toSet
argument_list|()
control|)
block|{
name|DocumentResource
name|docRes
init|=
name|factory
operator|.
name|getDocumentResource
argument_list|(
name|res
operator|.
name|asResource
argument_list|()
operator|.
name|getURI
argument_list|()
argument_list|)
decl_stmt|;
name|docs
operator|.
name|add
argument_list|(
name|docRes
argument_list|)
expr_stmt|;
block|}
return|return
name|Collections
operator|.
name|unmodifiableSet
argument_list|(
name|docs
argument_list|)
return|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|addRelatedDocument
parameter_list|(
name|DocumentResource
name|documentResource
parameter_list|)
block|{
name|this
operator|.
name|addProperty
argument_list|(
name|SearchVocabulary
operator|.
name|RELATED_DOCUMENT
argument_list|,
name|factory
operator|.
name|getDocumentResource
argument_list|(
name|factory
operator|.
name|documentName
argument_list|(
name|documentResource
operator|.
name|getDocumentURI
argument_list|()
argument_list|,
name|documentResource
operator|.
name|getRelatedKeywords
argument_list|()
operator|.
name|get
argument_list|(
literal|0
argument_list|)
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|addRelatedClass
parameter_list|(
name|ClassResource
name|classResource
parameter_list|)
block|{
throw|throw
operator|new
name|UnsupportedOperationException
argument_list|()
throw|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|addRelatedIndividual
parameter_list|(
name|IndividualResource
name|individualResource
parameter_list|)
block|{
throw|throw
operator|new
name|UnsupportedOperationException
argument_list|()
throw|;
block|}
block|}
end_class

end_unit

