begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_package
package|package
name|eu
operator|.
name|iksproject
operator|.
name|fise
operator|.
name|interaction
package|;
end_package

begin_comment
comment|/*  * Copyright 2010  * German Research Center for Artificial Intelligence (DFKI)  * Department of Intelligent User Interfaces  * Germany  *   *     http://www.dfki.de/web/forschung/iui  *   * Licensed under the Apache License, Version 2.0 (the "License");  * you may not use this file except in compliance with the License.  * You may obtain a copy of the License at  *   *     http://www.apache.org/licenses/LICENSE-2.0  *   * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  *   * Authors:  *     Sebastian Germesin  *     Massimo Romanelli  *     Tilman Becker  */
end_comment

begin_import
import|import
name|eu
operator|.
name|iksproject
operator|.
name|fise
operator|.
name|interaction
operator|.
name|event
operator|.
name|EventManager
import|;
end_import

begin_import
import|import
name|eu
operator|.
name|iksproject
operator|.
name|fise
operator|.
name|interaction
operator|.
name|gui
operator|.
name|Gui
import|;
end_import

begin_import
import|import
name|eu
operator|.
name|iksproject
operator|.
name|fise
operator|.
name|interaction
operator|.
name|speech
operator|.
name|NL2Sparql
import|;
end_import

begin_import
import|import
name|eu
operator|.
name|iksproject
operator|.
name|fise
operator|.
name|interaction
operator|.
name|speech
operator|.
name|SpeechServer
import|;
end_import

begin_class
specifier|public
class|class
name|Start
block|{
specifier|public
specifier|static
specifier|final
name|boolean
name|USE_TTS
init|=
literal|false
decl_stmt|;
specifier|static
specifier|final
name|String
name|INITIAL_CLEREZZA_SERVER_HOST
init|=
literal|"localhost"
decl_stmt|;
specifier|static
specifier|final
name|int
name|INITIAL_CLEREZZA_SERVER_PORT
init|=
literal|8080
decl_stmt|;
specifier|static
specifier|final
name|String
name|INITIAL_CLEREZZA_SERVER_USERNAME
init|=
literal|"admin"
decl_stmt|;
specifier|static
specifier|final
name|String
name|INITIAL_CLEREZZA_SERVER_PASSWORD
init|=
literal|"admin"
decl_stmt|;
specifier|public
specifier|static
name|void
name|main
parameter_list|(
name|String
index|[]
name|args
parameter_list|)
block|{
name|Gui
name|gui
init|=
operator|new
name|Gui
argument_list|(
name|INITIAL_CLEREZZA_SERVER_HOST
argument_list|,
name|INITIAL_CLEREZZA_SERVER_PORT
argument_list|,
name|INITIAL_CLEREZZA_SERVER_USERNAME
argument_list|,
name|INITIAL_CLEREZZA_SERVER_PASSWORD
argument_list|)
decl_stmt|;
name|SpeechServer
name|speechServer
init|=
operator|new
name|SpeechServer
argument_list|()
decl_stmt|;
name|NL2Sparql
name|nl2sparql
init|=
operator|new
name|NL2Sparql
argument_list|()
decl_stmt|;
name|QueryManager
name|queryManager
init|=
operator|new
name|QueryManager
argument_list|(
name|INITIAL_CLEREZZA_SERVER_HOST
argument_list|,
name|INITIAL_CLEREZZA_SERVER_PORT
argument_list|,
name|INITIAL_CLEREZZA_SERVER_USERNAME
argument_list|,
name|INITIAL_CLEREZZA_SERVER_PASSWORD
argument_list|)
decl_stmt|;
name|EventManager
operator|.
name|addEventListener
argument_list|(
name|gui
argument_list|)
expr_stmt|;
name|EventManager
operator|.
name|addEventListener
argument_list|(
name|speechServer
argument_list|)
expr_stmt|;
name|EventManager
operator|.
name|addEventListener
argument_list|(
name|nl2sparql
argument_list|)
expr_stmt|;
name|EventManager
operator|.
name|addEventListener
argument_list|(
name|queryManager
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

