begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|entityhub
operator|.
name|ldpath
operator|.
name|impl
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|commons
operator|.
name|solr
operator|.
name|managed
operator|.
name|standalone
operator|.
name|ClassPathDataFileProvider
import|;
end_import

begin_class
specifier|public
class|class
name|DbPediaDatadefaultDataFileProvider
extends|extends
name|ClassPathDataFileProvider
block|{
specifier|private
specifier|static
specifier|final
name|String
name|DATA_FILES_DIR
init|=
literal|"org/apache/stanbol/data/site/dbpedia/default/index/"
decl_stmt|;
specifier|public
name|DbPediaDatadefaultDataFileProvider
parameter_list|()
block|{
name|super
argument_list|(
literal|null
argument_list|,
name|DATA_FILES_DIR
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

