begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/* * Licensed to the Apache Software Foundation (ASF) under one or more * contributor license agreements.  See the NOTICE file distributed with * this work for additional information regarding copyright ownership. * The ASF licenses this file to You under the Apache License, Version 2.0 * (the "License"); you may not use this file except in compliance with * the License.  You may obtain a copy of the License at * *     http://www.apache.org/licenses/LICENSE-2.0 * * Unless required by applicable law or agreed to in writing, software * distributed under the License is distributed on an "AS IS" BASIS, * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. * See the License for the specific language governing permissions and * limitations under the License. */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|launchpad
package|;
end_package

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|sling
operator|.
name|launchpad
operator|.
name|base
operator|.
name|shared
operator|.
name|SharedConstants
operator|.
name|SLING_HOME
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|File
import|;
end_import

begin_class
specifier|public
class|class
name|Main
block|{
specifier|public
specifier|static
specifier|final
name|String
name|DEFAULT_STANBOL_HOME
init|=
literal|"stanbol"
decl_stmt|;
comment|/**      * @param args      */
specifier|public
specifier|static
name|void
name|main
parameter_list|(
name|String
index|[]
name|args
parameter_list|)
block|{
name|String
name|home
init|=
name|System
operator|.
name|getProperties
argument_list|()
operator|.
name|getProperty
argument_list|(
name|SLING_HOME
argument_list|)
decl_stmt|;
if|if
condition|(
name|home
operator|==
literal|null
condition|)
block|{
name|home
operator|=
operator|new
name|File
argument_list|(
name|DEFAULT_STANBOL_HOME
argument_list|)
operator|.
name|getAbsolutePath
argument_list|()
expr_stmt|;
name|System
operator|.
name|setProperty
argument_list|(
name|SLING_HOME
argument_list|,
name|home
argument_list|)
expr_stmt|;
block|}
comment|//else do not override user configured values
comment|//now use the standard Apache Sling launcher to do the job
name|org
operator|.
name|apache
operator|.
name|sling
operator|.
name|launchpad
operator|.
name|app
operator|.
name|Main
operator|.
name|main
argument_list|(
name|args
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

