begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|ontologymanager
operator|.
name|ontonet
operator|.
name|impl
operator|.
name|clerezza
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|BufferedInputStream
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|InputStream
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|clerezza
operator|.
name|rdf
operator|.
name|core
operator|.
name|MGraph
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|clerezza
operator|.
name|rdf
operator|.
name|core
operator|.
name|UriRef
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|clerezza
operator|.
name|rdf
operator|.
name|core
operator|.
name|access
operator|.
name|TcManager
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|clerezza
operator|.
name|rdf
operator|.
name|core
operator|.
name|impl
operator|.
name|TripleImpl
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|clerezza
operator|.
name|rdf
operator|.
name|core
operator|.
name|serializedform
operator|.
name|Parser
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|clerezza
operator|.
name|rdf
operator|.
name|ontologies
operator|.
name|OWL
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|clerezza
operator|.
name|rdf
operator|.
name|ontologies
operator|.
name|RDF
import|;
end_import

begin_import
import|import
name|org
operator|.
name|semanticweb
operator|.
name|owlapi
operator|.
name|model
operator|.
name|IRI
import|;
end_import

begin_import
import|import
name|org
operator|.
name|semanticweb
operator|.
name|owlapi
operator|.
name|model
operator|.
name|OWLOntologyID
import|;
end_import

begin_import
import|import
name|org
operator|.
name|slf4j
operator|.
name|Logger
import|;
end_import

begin_import
import|import
name|org
operator|.
name|slf4j
operator|.
name|LoggerFactory
import|;
end_import

begin_comment
comment|/**  * A set of utilities for handling OWL2 ontologies in Clerezza.  *   * @author alexdma  *   */
end_comment

begin_class
specifier|public
class|class
name|ClerezzaOWLUtils
block|{
specifier|private
specifier|static
name|Logger
name|log
init|=
name|LoggerFactory
operator|.
name|getLogger
argument_list|(
name|ClerezzaOWLUtils
operator|.
name|class
argument_list|)
decl_stmt|;
specifier|public
specifier|static
name|MGraph
name|createOntology
parameter_list|(
name|String
name|id
parameter_list|,
name|TcManager
name|tcm
parameter_list|)
block|{
name|UriRef
name|name
init|=
operator|new
name|UriRef
argument_list|(
name|id
argument_list|)
decl_stmt|;
name|MGraph
name|ont
init|=
name|tcm
operator|.
name|createMGraph
argument_list|(
name|name
argument_list|)
decl_stmt|;
name|ont
operator|.
name|add
argument_list|(
operator|new
name|TripleImpl
argument_list|(
name|name
argument_list|,
name|RDF
operator|.
name|type
argument_list|,
name|OWL
operator|.
name|Ontology
argument_list|)
argument_list|)
expr_stmt|;
return|return
name|ont
return|;
block|}
specifier|public
specifier|static
name|MGraph
name|createOntology
parameter_list|(
name|String
name|id
parameter_list|)
block|{
return|return
name|createOntology
argument_list|(
name|id
argument_list|,
name|TcManager
operator|.
name|getInstance
argument_list|()
argument_list|)
return|;
block|}
comment|/**      * Performs lookahead with a 100 kB limit.      *       * @param content      * @param parser      * @param format      * @return      * @throws IOException      */
specifier|public
specifier|static
name|OWLOntologyID
name|guessOntologyID
parameter_list|(
name|InputStream
name|content
parameter_list|,
name|Parser
name|parser
parameter_list|,
name|String
name|format
parameter_list|)
throws|throws
name|IOException
block|{
return|return
name|guessOntologyID
argument_list|(
name|content
argument_list|,
name|parser
argument_list|,
name|format
argument_list|,
literal|100
operator|*
literal|1024
argument_list|)
return|;
block|}
specifier|public
specifier|static
name|OWLOntologyID
name|guessOntologyID
parameter_list|(
name|InputStream
name|content
parameter_list|,
name|Parser
name|parser
parameter_list|,
name|String
name|format
parameter_list|,
name|int
name|limit
parameter_list|)
throws|throws
name|IOException
block|{
name|BufferedInputStream
name|bIn
init|=
operator|new
name|BufferedInputStream
argument_list|(
name|content
argument_list|)
decl_stmt|;
name|bIn
operator|.
name|mark
argument_list|(
name|limit
argument_list|)
expr_stmt|;
comment|// set an appropriate limit
name|OntologyLookaheadMGraph
name|graph
init|=
operator|new
name|OntologyLookaheadMGraph
argument_list|()
decl_stmt|;
try|try
block|{
name|parser
operator|.
name|parse
argument_list|(
name|graph
argument_list|,
name|bIn
argument_list|,
name|format
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|RuntimeException
name|e
parameter_list|)
block|{}
if|if
condition|(
name|graph
operator|.
name|getOntologyIRI
argument_list|()
operator|!=
literal|null
condition|)
block|{
comment|// bIn.reset(); // reset set the stream to the start
return|return
operator|new
name|OWLOntologyID
argument_list|(
name|IRI
operator|.
name|create
argument_list|(
name|graph
operator|.
name|getOntologyIRI
argument_list|()
operator|.
name|getUnicodeString
argument_list|()
argument_list|)
argument_list|)
return|;
block|}
else|else
block|{
comment|// No OntologyID found
comment|// do some error handling
name|log
operator|.
name|warn
argument_list|(
literal|"No ontologyID found after {} bytes, ontology has a chance of being anonymous."
argument_list|,
name|limit
argument_list|)
expr_stmt|;
return|return
literal|null
return|;
block|}
block|}
block|}
end_class

end_unit

