begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|ontologymanager
operator|.
name|ontonet
operator|.
name|api
operator|.
name|ontology
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|InputStream
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Set
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|clerezza
operator|.
name|rdf
operator|.
name|core
operator|.
name|access
operator|.
name|TcProvider
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|clerezza
operator|.
name|rdf
operator|.
name|core
operator|.
name|serializedform
operator|.
name|UnsupportedFormatException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|semanticweb
operator|.
name|owlapi
operator|.
name|model
operator|.
name|IRI
import|;
end_import

begin_import
import|import
name|org
operator|.
name|semanticweb
operator|.
name|owlapi
operator|.
name|model
operator|.
name|OWLOntologyManager
import|;
end_import

begin_comment
comment|/**  * A system responsible for maintaining registry ontologies. Depending on the implementation, it can be  * volatile or persistent, centralised or distributed.<br>  *<br>  * TODO see if full CRUD operation support is necessary. TODO deprecate methods that expose keys. These should  * all be handled internally.  *   * @author alexdma  *   * @param<S>  *            the storage system actually used by this provider.  */
end_comment

begin_interface
specifier|public
interface|interface
name|OntologyProvider
parameter_list|<
name|S
parameter_list|>
block|{
comment|/**      * The key used to configure the prefix to be used for addressing ontologies stored by this provider.      */
specifier|public
name|String
name|GRAPH_PREFIX
init|=
literal|"org.apache.stanbol.ontologymanager.ontonet.graphPrefix"
decl_stmt|;
comment|/**      * The key used to configure the default import resolution policy for this provider.      */
specifier|public
name|String
name|RESOLVE_IMPORTS
init|=
literal|"org.apache.stanbol.ontologymanager.ontonet.resolveImports"
decl_stmt|;
name|String
name|getKey
parameter_list|(
name|IRI
name|ontologyIRI
parameter_list|)
function_decl|;
name|Set
argument_list|<
name|String
argument_list|>
name|getKeys
parameter_list|()
function_decl|;
comment|/**      * Returns the storage system used by this ontology provider (e.g. a {@link TcProvider} or an      * {@link OWLOntologyManager}).      *       * @return the ontology store.      */
name|S
name|getStore
parameter_list|()
function_decl|;
comment|/**      * Same as {@link OntologyProvider#getStoredOntology(String, Class)}, but instead of the internal key it      * uses an IRI that<i>publicly</i> identifies or references an ontology. This can be, ordered by      * preference most relevant first:      *<ol>      *<li>The version IRI      *<li>The ontology IRI      *<li>The physical IRI, if different from the above      *</ol>      *       * @param reference      * @param returnType      * @return      */
parameter_list|<
name|O
parameter_list|>
name|O
name|getStoredOntology
parameter_list|(
name|IRI
name|reference
parameter_list|,
name|Class
argument_list|<
name|O
argument_list|>
name|returnType
parameter_list|)
function_decl|;
parameter_list|<
name|O
parameter_list|>
name|O
name|getStoredOntology
parameter_list|(
name|IRI
name|reference
parameter_list|,
name|Class
argument_list|<
name|O
argument_list|>
name|returnType
parameter_list|,
name|boolean
name|merge
parameter_list|)
function_decl|;
comment|/**      *       *       * @param key      *            the key used to identify the ontology in this provider. They can or cannot coincide with the      *            logical and/or physical IRI of the ontology.      * @param returnType      *            The expected type for the returned ontology object. If null, the provider will arbitrarily      *            select a supported return type. If the supplied type is not supported (i.e. not assignable      *            to any type contained in the result of {@link #getSupportedReturnTypes()}) an      *            {@link UnsupportedOperationException} should be thrown.      * @return      */
parameter_list|<
name|O
parameter_list|>
name|O
name|getStoredOntology
parameter_list|(
name|String
name|key
parameter_list|,
name|Class
argument_list|<
name|O
argument_list|>
name|returnType
parameter_list|)
function_decl|;
parameter_list|<
name|O
parameter_list|>
name|O
name|getStoredOntology
parameter_list|(
name|String
name|key
parameter_list|,
name|Class
argument_list|<
name|O
argument_list|>
name|returnType
parameter_list|,
name|boolean
name|merge
parameter_list|)
function_decl|;
comment|/**      * Returns an array containing the most specific types for ontology objects that this provider can manage      * and return on a call to {@link #getStoredOntology(String, Class)}.      *       * @return the supported ontology return types.      */
parameter_list|<
name|O
parameter_list|>
name|Class
argument_list|<
name|O
argument_list|>
index|[]
name|getSupportedReturnTypes
parameter_list|()
function_decl|;
comment|/**      * Retrieves an ontology by reading its content from a data stream and stores it using the storage system      * attached to this provider. A key that can be used to identify the ontology in this provider is returned      * if successful.      *       * @param data      *            the ontology content.      * @param formatIdentifier      *            the MIME type of the expected serialization format of this ontology. If null, all supported      *            formats will be tried until all parsers fail or one succeeds.      * @param force      *            if true, all mappings provided by the offline configuration will be ignored (both for the      *            root ontology and its recursive imports) and the provider will forcibly try to resolve the      *            location IRI. If some remote import is found, the import policy is aggressive and Stanbol is      *            set on offline mode, this method will fail.      * @return a key that can be used to retrieve the stored ontology afterwards, or null if loading/storage      *         failed.      * @throws IOException      *             if all attempts to load the ontology failed.      * @throws UnsupportedFormatException      *             if no parsers are able to parse the supplied format (or the actual file format).      */
name|String
name|loadInStore
parameter_list|(
name|InputStream
name|data
parameter_list|,
name|String
name|formatIdentifier
parameter_list|,
name|String
name|preferredKey
parameter_list|,
name|boolean
name|force
parameter_list|)
throws|throws
name|IOException
throws|,
name|UnsupportedFormatException
function_decl|;
comment|/**      * Retrieves an ontology physically located at<code>location</code> (unless mapped otherwise by the      * offline configuration) and stores it using the storage system attached to this provider. A key that can      * be used to identify the ontology in this provider is returned if successful.      *       * @param location      *            the physical IRI where the ontology is located.      * @param formatIdentifier      *            the MIME type of the expected serialization format of this ontology. If null, all supported      *            formats will be tried until all parsers fail or one succeeds.      * @param force      *            if true, all mappings provided by the offline configuration will be ignored (both for the      *            root ontology and its recursive imports) and the provider will forcibly try to resolve the      *            location IRI. If the IRI is not local and Stanbol is set on offline mode, this method will      *            fail.      * @return a key that can be used to retrieve the stored ontology afterwards, or null if loading/storage      *         failed.      * @throws IOException      *             if all attempts to load the ontology failed.      * @throws UnsupportedFormatException      *             if no parsers are able to parse the supplied format (or the actual file format).      */
name|String
name|loadInStore
parameter_list|(
name|IRI
name|location
parameter_list|,
name|String
name|formatIdentifier
parameter_list|,
name|String
name|preferredKey
parameter_list|,
name|boolean
name|force
parameter_list|)
throws|throws
name|IOException
throws|,
name|UnsupportedFormatException
function_decl|;
name|String
name|loadInStore
parameter_list|(
name|Object
name|ontology
parameter_list|,
name|String
name|preferredKey
parameter_list|,
name|boolean
name|force
parameter_list|)
function_decl|;
block|}
end_interface

end_unit

