begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|//
end_comment

begin_comment
comment|// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs
end_comment

begin_comment
comment|// See<a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
end_comment

begin_comment
comment|// Any modifications to this file will be lost upon recompilation of the source schema.
end_comment

begin_comment
comment|// Generated on: 2011.04.29 at 11:44:48 AM EEST
end_comment

begin_comment
comment|//
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|cmsadapter
operator|.
name|servicesapi
operator|.
name|model
operator|.
name|web
package|;
end_package

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|bind
operator|.
name|annotation
operator|.
name|XmlAccessType
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|bind
operator|.
name|annotation
operator|.
name|XmlAccessorType
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|bind
operator|.
name|annotation
operator|.
name|XmlElement
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|bind
operator|.
name|annotation
operator|.
name|XmlRootElement
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|bind
operator|.
name|annotation
operator|.
name|XmlType
import|;
end_import

begin_comment
comment|/**  *<p>Java class for childObjectDefinition element declaration.  *   *<p>The following schema fragment specifies the expected content contained within this class.  *   *<pre>  *&lt;element name="childObjectDefinition">  *&lt;complexType>  *&lt;complexContent>  *&lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">  *&lt;sequence>  *&lt;element ref="{web.model.servicesapi.cmsadapter.stanbol.apache.org}allowedObjectTypeDefRef"/>  *&lt;element ref="{web.model.servicesapi.cmsadapter.stanbol.apache.org}required" minOccurs="0"/>  *&lt;/sequence>  *&lt;/restriction>  *&lt;/complexContent>  *&lt;/complexType>  *&lt;/element>  *</pre>  *   *   */
end_comment

begin_class
annotation|@
name|XmlAccessorType
argument_list|(
name|XmlAccessType
operator|.
name|FIELD
argument_list|)
annotation|@
name|XmlType
argument_list|(
name|name
operator|=
literal|""
argument_list|,
name|propOrder
operator|=
block|{
literal|"allowedObjectTypeDefRef"
block|,
literal|"required"
block|}
argument_list|)
annotation|@
name|XmlRootElement
argument_list|(
name|name
operator|=
literal|"childObjectDefinition"
argument_list|)
specifier|public
class|class
name|ChildObjectDefinition
block|{
annotation|@
name|XmlElement
argument_list|(
name|namespace
operator|=
literal|"web.model.servicesapi.cmsadapter.stanbol.apache.org"
argument_list|,
name|required
operator|=
literal|true
argument_list|)
specifier|protected
name|String
name|allowedObjectTypeDefRef
decl_stmt|;
annotation|@
name|XmlElement
argument_list|(
name|namespace
operator|=
literal|"web.model.servicesapi.cmsadapter.stanbol.apache.org"
argument_list|)
specifier|protected
name|Boolean
name|required
decl_stmt|;
comment|/**      * Gets the value of the allowedObjectTypeDefRef property.      *       * @return      *     possible object is      *     {@link String }      *           */
specifier|public
name|String
name|getAllowedObjectTypeDefRef
parameter_list|()
block|{
return|return
name|allowedObjectTypeDefRef
return|;
block|}
comment|/**      * Sets the value of the allowedObjectTypeDefRef property.      *       * @param value      *     allowed object is      *     {@link String }      *           */
specifier|public
name|void
name|setAllowedObjectTypeDefRef
parameter_list|(
name|String
name|value
parameter_list|)
block|{
name|this
operator|.
name|allowedObjectTypeDefRef
operator|=
name|value
expr_stmt|;
block|}
comment|/**      * Gets the value of the required property.      *       * @return      *     possible object is      *     {@link Boolean }      *           */
specifier|public
name|Boolean
name|isRequired
parameter_list|()
block|{
return|return
name|required
return|;
block|}
comment|/**      * Sets the value of the required property.      *       * @param value      *     allowed object is      *     {@link Boolean }      *           */
specifier|public
name|void
name|setRequired
parameter_list|(
name|Boolean
name|value
parameter_list|)
block|{
name|this
operator|.
name|required
operator|=
name|value
expr_stmt|;
block|}
block|}
end_class

end_unit

