begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|//
end_comment

begin_comment
comment|// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3-
end_comment

begin_comment
comment|// See<a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
end_comment

begin_comment
comment|// Any modifications to this file will be lost upon recompilation of the source schema.
end_comment

begin_comment
comment|// Generated on: 2011.05.17 at 10:53:39 AM EEST
end_comment

begin_comment
comment|//
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|cmsadapter
operator|.
name|servicesapi
operator|.
name|model
operator|.
name|web
package|;
end_package

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|bind
operator|.
name|annotation
operator|.
name|XmlEnum
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|bind
operator|.
name|annotation
operator|.
name|XmlType
import|;
end_import

begin_comment
comment|/**  *<p>Java class for propType.  *   *<p>The following schema fragment specifies the expected content contained within this class.  *<p>  *<pre>  *&lt;simpleType name="propType">  *&lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">  *&lt;enumeration value="STRING"/>  *&lt;enumeration value="BOOLEAN"/>  *&lt;enumeration value="DECIMAL"/>  *&lt;enumeration value="INTEGER"/>  *&lt;enumeration value="DATE"/>  *&lt;enumeration value="URI"/>  *&lt;enumeration value="HTML"/>  *&lt;enumeration value="REFERENCE"/>  *&lt;enumeration value="WEAKREFERENCE"/>  *&lt;enumeration value="LONG"/>  *&lt;enumeration value="DOUBLE"/>  *&lt;enumeration value="BINARY"/>  *&lt;enumeration value="PATH"/>  *&lt;enumeration value="NAME"/>  *&lt;enumeration value="UNDEFINED"/>  *&lt;/restriction>  *&lt;/simpleType>  *</pre>  *   */
end_comment

begin_enum
annotation|@
name|XmlType
argument_list|(
name|name
operator|=
literal|"propType"
argument_list|)
annotation|@
name|XmlEnum
specifier|public
enum|enum
name|PropType
block|{
name|STRING
block|,
name|BOOLEAN
block|,
name|DECIMAL
block|,
name|INTEGER
block|,
name|DATE
block|,
name|URI
block|,
name|HTML
block|,
name|REFERENCE
block|,
name|WEAKREFERENCE
block|,
name|LONG
block|,
name|DOUBLE
block|,
name|BINARY
block|,
name|PATH
block|,
name|NAME
block|,
name|UNDEFINED
block|;
specifier|public
name|String
name|value
parameter_list|()
block|{
return|return
name|name
argument_list|()
return|;
block|}
specifier|public
specifier|static
name|PropType
name|fromValue
parameter_list|(
name|String
name|v
parameter_list|)
block|{
return|return
name|valueOf
argument_list|(
name|v
argument_list|)
return|;
block|}
block|}
end_enum

end_unit

