begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/* * Licensed to the Apache Software Foundation (ASF) under one or more * contributor license agreements.  See the NOTICE file distributed with * this work for additional information regarding copyright ownership. * The ASF licenses this file to You under the Apache License, Version 2.0 * (the "License"); you may not use this file except in compliance with * the License.  You may obtain a copy of the License at * *     http://www.apache.org/licenses/LICENSE-2.0 * * Unless required by applicable law or agreed to in writing, software * distributed under the License is distributed on an "AS IS" BASIS, * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. * See the License for the specific language governing permissions and * limitations under the License. */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|engines
operator|.
name|entitycomention
package|;
end_package

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|engines
operator|.
name|entitylinking
operator|.
name|config
operator|.
name|EntityLinkerConfig
operator|.
name|CASE_SENSITIVE
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|engines
operator|.
name|entitylinking
operator|.
name|config
operator|.
name|EntityLinkerConfig
operator|.
name|DEFAULT_CASE_SENSITIVE_MATCHING_STATE
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|engines
operator|.
name|entitylinking
operator|.
name|config
operator|.
name|TextProcessingConfig
operator|.
name|DEFAULT_PROCESS_ONLY_PROPER_NOUNS_STATE
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|engines
operator|.
name|entitylinking
operator|.
name|config
operator|.
name|TextProcessingConfig
operator|.
name|PROCESSED_LANGUAGES
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|engines
operator|.
name|entitylinking
operator|.
name|config
operator|.
name|TextProcessingConfig
operator|.
name|PROCESS_ONLY_PROPER_NOUNS_STATE
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|nlp
operator|.
name|utils
operator|.
name|NlpEngineHelper
operator|.
name|getAnalysedText
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|nlp
operator|.
name|utils
operator|.
name|NlpEngineHelper
operator|.
name|getLanguage
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|servicesapi
operator|.
name|EnhancementEngine
operator|.
name|PROPERTY_NAME
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|servicesapi
operator|.
name|helper
operator|.
name|EnhancementEngineHelper
operator|.
name|getReferences
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|servicesapi
operator|.
name|rdf
operator|.
name|Properties
operator|.
name|DC_CONTRIBUTOR
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|servicesapi
operator|.
name|rdf
operator|.
name|Properties
operator|.
name|DC_RELATION
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|servicesapi
operator|.
name|rdf
operator|.
name|Properties
operator|.
name|DC_TYPE
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|servicesapi
operator|.
name|rdf
operator|.
name|Properties
operator|.
name|ENHANCER_CONFIDENCE
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|servicesapi
operator|.
name|rdf
operator|.
name|Properties
operator|.
name|ENHANCER_END
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|servicesapi
operator|.
name|rdf
operator|.
name|Properties
operator|.
name|ENHANCER_ENTITY_REFERENCE
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|servicesapi
operator|.
name|rdf
operator|.
name|Properties
operator|.
name|ENHANCER_START
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|servicesapi
operator|.
name|rdf
operator|.
name|Properties
operator|.
name|RDF_TYPE
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|servicesapi
operator|.
name|rdf
operator|.
name|TechnicalClasses
operator|.
name|ENHANCER_TEXTANNOTATION
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|osgi
operator|.
name|framework
operator|.
name|Constants
operator|.
name|SERVICE_RANKING
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|ArrayList
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Collection
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Collections
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Dictionary
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|HashMap
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|HashSet
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Iterator
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Map
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Map
operator|.
name|Entry
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Set
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|clerezza
operator|.
name|rdf
operator|.
name|core
operator|.
name|Language
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|clerezza
operator|.
name|rdf
operator|.
name|core
operator|.
name|Literal
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|clerezza
operator|.
name|rdf
operator|.
name|core
operator|.
name|LiteralFactory
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|clerezza
operator|.
name|rdf
operator|.
name|core
operator|.
name|MGraph
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|clerezza
operator|.
name|rdf
operator|.
name|core
operator|.
name|NonLiteral
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|clerezza
operator|.
name|rdf
operator|.
name|core
operator|.
name|Resource
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|clerezza
operator|.
name|rdf
operator|.
name|core
operator|.
name|Triple
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|clerezza
operator|.
name|rdf
operator|.
name|core
operator|.
name|UriRef
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|clerezza
operator|.
name|rdf
operator|.
name|core
operator|.
name|impl
operator|.
name|PlainLiteralImpl
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|clerezza
operator|.
name|rdf
operator|.
name|core
operator|.
name|impl
operator|.
name|TripleImpl
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|commons
operator|.
name|lang
operator|.
name|StringUtils
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|felix
operator|.
name|scr
operator|.
name|annotations
operator|.
name|Activate
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|felix
operator|.
name|scr
operator|.
name|annotations
operator|.
name|Component
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|felix
operator|.
name|scr
operator|.
name|annotations
operator|.
name|ConfigurationPolicy
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|felix
operator|.
name|scr
operator|.
name|annotations
operator|.
name|Deactivate
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|felix
operator|.
name|scr
operator|.
name|annotations
operator|.
name|Property
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|felix
operator|.
name|scr
operator|.
name|annotations
operator|.
name|Reference
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|felix
operator|.
name|scr
operator|.
name|annotations
operator|.
name|Service
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|commons
operator|.
name|namespaceprefix
operator|.
name|NamespacePrefixService
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|engines
operator|.
name|entitycomention
operator|.
name|impl
operator|.
name|ContentItemMentionBuilder
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|engines
operator|.
name|entitylinking
operator|.
name|Entity
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|engines
operator|.
name|entitylinking
operator|.
name|EntitySearcherException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|engines
operator|.
name|entitylinking
operator|.
name|LabelTokenizer
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|engines
operator|.
name|entitylinking
operator|.
name|config
operator|.
name|EntityLinkerConfig
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|engines
operator|.
name|entitylinking
operator|.
name|config
operator|.
name|EntityLinkerConfig
operator|.
name|RedirectProcessingMode
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|engines
operator|.
name|entitylinking
operator|.
name|config
operator|.
name|LanguageProcessingConfig
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|engines
operator|.
name|entitylinking
operator|.
name|config
operator|.
name|TextProcessingConfig
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|engines
operator|.
name|entitylinking
operator|.
name|impl
operator|.
name|EntityLinker
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|engines
operator|.
name|entitylinking
operator|.
name|impl
operator|.
name|LinkedEntity
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|engines
operator|.
name|entitylinking
operator|.
name|impl
operator|.
name|LinkedEntity
operator|.
name|Occurrence
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|engines
operator|.
name|entitylinking
operator|.
name|impl
operator|.
name|Suggestion
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|nlp
operator|.
name|model
operator|.
name|AnalysedText
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|servicesapi
operator|.
name|ContentItem
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|servicesapi
operator|.
name|EngineException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|servicesapi
operator|.
name|EnhancementEngine
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|servicesapi
operator|.
name|ServiceProperties
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|servicesapi
operator|.
name|helper
operator|.
name|EnhancementEngineHelper
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|servicesapi
operator|.
name|impl
operator|.
name|AbstractEnhancementEngine
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|servicesapi
operator|.
name|rdf
operator|.
name|Properties
import|;
end_import

begin_import
import|import
name|org
operator|.
name|osgi
operator|.
name|service
operator|.
name|cm
operator|.
name|ConfigurationException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|osgi
operator|.
name|service
operator|.
name|component
operator|.
name|ComponentContext
import|;
end_import

begin_import
import|import
name|org
operator|.
name|slf4j
operator|.
name|Logger
import|;
end_import

begin_import
import|import
name|org
operator|.
name|slf4j
operator|.
name|LoggerFactory
import|;
end_import

begin_comment
comment|/**  * The Entity Co-Mentiaon Engine builds a local knowledge base already extracted  *<code>fise:TextAnnotation</code>s and suggested   *<code>fise:EntityAnnotation</code>s. This information are then used to perform  * an entity linking process. By doing so this engine will be able to detect  * Co-Mentions of Entities within the processed document.<p>  *   *   *   * @author Rupert Westenthaler  *  */
end_comment

begin_class
annotation|@
name|Component
argument_list|(
name|configurationFactory
operator|=
literal|true
argument_list|,
name|policy
operator|=
name|ConfigurationPolicy
operator|.
name|REQUIRE
argument_list|,
comment|// the baseUri is required!
name|specVersion
operator|=
literal|"1.1"
argument_list|,
name|metatype
operator|=
literal|true
argument_list|,
name|immediate
operator|=
literal|true
argument_list|,
name|inherit
operator|=
literal|true
argument_list|)
annotation|@
name|org
operator|.
name|apache
operator|.
name|felix
operator|.
name|scr
operator|.
name|annotations
operator|.
name|Properties
argument_list|(
name|value
operator|=
block|{
annotation|@
name|Property
argument_list|(
name|name
operator|=
name|PROPERTY_NAME
argument_list|)
block|,
annotation|@
name|Property
argument_list|(
name|name
operator|=
name|CASE_SENSITIVE
argument_list|,
name|boolValue
operator|=
name|DEFAULT_CASE_SENSITIVE_MATCHING_STATE
argument_list|)
block|,
annotation|@
name|Property
argument_list|(
name|name
operator|=
name|PROCESS_ONLY_PROPER_NOUNS_STATE
argument_list|,
name|boolValue
operator|=
name|DEFAULT_PROCESS_ONLY_PROPER_NOUNS_STATE
argument_list|)
block|,
annotation|@
name|Property
argument_list|(
name|name
operator|=
name|PROCESSED_LANGUAGES
argument_list|,
name|cardinality
operator|=
name|Integer
operator|.
name|MAX_VALUE
argument_list|,
name|value
operator|=
block|{
literal|"*;lmmtip;uc=LINK;prop=0.75;pprob=0.75"
block|,
comment|// link multiple matchable tokens in chunks; link upper case words
literal|"de;uc=MATCH"
block|,
comment|//in German all Nouns are upper case
literal|"es;lc=Noun"
block|,
comment|//the OpenNLP POS tagger for Spanish does not support ProperNouns
literal|"nl;lc=Noun"
block|}
argument_list|)
block|,
comment|//same for Dutch
annotation|@
name|Property
argument_list|(
name|name
operator|=
name|EntityCoMentionEngine
operator|.
name|ADJUST_EXISTING_SUGGESTION_CONFIDENCE
argument_list|,
name|doubleValue
operator|=
name|EntityCoMentionEngine
operator|.
name|DEFAULT_CONFIDENCE_ADJUSTEMENT
argument_list|)
block|,
annotation|@
name|Property
argument_list|(
name|name
operator|=
name|SERVICE_RANKING
argument_list|,
name|intValue
operator|=
literal|0
argument_list|)
block|}
argument_list|)
annotation|@
name|Service
argument_list|(
name|value
operator|=
name|EnhancementEngine
operator|.
name|class
argument_list|)
specifier|public
class|class
name|EntityCoMentionEngine
extends|extends
name|AbstractEnhancementEngine
argument_list|<
name|RuntimeException
argument_list|,
name|RuntimeException
argument_list|>
implements|implements
name|ServiceProperties
block|{
comment|/** 	 * Property used to configure if/how confidence values of existing suggestions 	 * are modified if a co-mention is detected for a fise:TextAnnotation.<p> 	 * Values MUST be in the range [0..1) the  	 * {@link #DEFAULT_CONFIDENCE_ADJUSTEMENT default} is<code>0.33</code><p> 	 * Added with<a href="https://issues.apache.org/jira/browse/STANBOL-1219">STANBOL-1219</a> 	 */
specifier|public
specifier|static
specifier|final
name|String
name|ADJUST_EXISTING_SUGGESTION_CONFIDENCE
init|=
literal|"enhancer.engines.comention.adjustExistingConfidence"
decl_stmt|;
comment|/**      * Default value for {@link #ADJUST_EXISTING_SUGGESTION_CONFIDENCE}      */
specifier|public
specifier|static
specifier|final
name|double
name|DEFAULT_CONFIDENCE_ADJUSTEMENT
init|=
literal|0.33
decl_stmt|;
comment|/**      * first of the post processing engines (note STANBOL-1218)      */
specifier|private
specifier|static
specifier|final
name|Integer
name|ENGINE_ORDERING
init|=
name|ServiceProperties
operator|.
name|ORDERING_POST_PROCESSING
operator|+
literal|80
decl_stmt|;
specifier|private
specifier|static
specifier|final
name|Map
argument_list|<
name|String
argument_list|,
name|Object
argument_list|>
name|SERVICE_PROPERTIES
init|=
name|Collections
operator|.
name|unmodifiableMap
argument_list|(
name|Collections
operator|.
name|singletonMap
argument_list|(
name|ServiceProperties
operator|.
name|ENHANCEMENT_ENGINE_ORDERING
argument_list|,
operator|(
name|Object
operator|)
name|ENGINE_ORDERING
argument_list|)
argument_list|)
decl_stmt|;
specifier|private
specifier|final
name|Logger
name|log
init|=
name|LoggerFactory
operator|.
name|getLogger
argument_list|(
name|EntityCoMentionEngine
operator|.
name|class
argument_list|)
decl_stmt|;
specifier|private
specifier|final
name|LiteralFactory
name|literalFactory
init|=
name|LiteralFactory
operator|.
name|getInstance
argument_list|()
decl_stmt|;
annotation|@
name|Reference
specifier|protected
name|NamespacePrefixService
name|prefixService
decl_stmt|;
annotation|@
name|Reference
specifier|protected
name|LabelTokenizer
name|labelTokenizer
decl_stmt|;
specifier|private
name|double
name|confidenceAdjustmentFactor
decl_stmt|;
comment|//    private BundleContext bundleContext;
comment|/**      * EntityLinking configuration used for Co-Mention extractions      */
specifier|private
name|EntityLinkerConfig
name|linkerConfig
decl_stmt|;
comment|/**      * TextProcessingConfig used for Co-Mention extraction      */
specifier|private
name|TextProcessingConfig
name|textProcessingConfig
decl_stmt|;
comment|/**      * Default constructor as used by OSGI. This expects that       * {@link #activate(ComponentContext)} is called before usage      */
specifier|public
name|EntityCoMentionEngine
parameter_list|()
block|{     }
annotation|@
name|Activate
annotation|@
name|SuppressWarnings
argument_list|(
literal|"unchecked"
argument_list|)
specifier|protected
name|void
name|activate
parameter_list|(
name|ComponentContext
name|ctx
parameter_list|)
throws|throws
name|ConfigurationException
block|{
name|super
operator|.
name|activate
argument_list|(
name|ctx
argument_list|)
expr_stmt|;
name|log
operator|.
name|info
argument_list|(
literal|"activate {}[name:{}]"
argument_list|,
name|getClass
argument_list|()
operator|.
name|getSimpleName
argument_list|()
argument_list|,
name|getName
argument_list|()
argument_list|)
expr_stmt|;
name|Dictionary
argument_list|<
name|String
argument_list|,
name|Object
argument_list|>
name|properties
init|=
name|ctx
operator|.
name|getProperties
argument_list|()
decl_stmt|;
comment|//        bundleContext = ctx.getBundleContext();
comment|//extract TextProcessing and EnityLinking config from the provided properties
name|textProcessingConfig
operator|=
name|TextProcessingConfig
operator|.
name|createInstance
argument_list|(
name|properties
argument_list|)
expr_stmt|;
name|linkerConfig
operator|=
name|EntityLinkerConfig
operator|.
name|createInstance
argument_list|(
name|properties
argument_list|,
name|prefixService
argument_list|)
expr_stmt|;
comment|//some of the confiugration is predefined
name|linkerConfig
operator|.
name|setNameField
argument_list|(
name|CoMentionConstants
operator|.
name|CO_MENTION_LABEL_FIELD
argument_list|)
expr_stmt|;
name|linkerConfig
operator|.
name|setTypeField
argument_list|(
name|CoMentionConstants
operator|.
name|CO_MENTION_TYPE_FIELD
argument_list|)
expr_stmt|;
name|linkerConfig
operator|.
name|setMaxSuggestions
argument_list|(
literal|5
argument_list|)
expr_stmt|;
comment|//there should not be more as 5 suggestions
name|linkerConfig
operator|.
name|setMinFoundTokens
argument_list|(
literal|1
argument_list|)
expr_stmt|;
comment|//a single token is enough
name|linkerConfig
operator|.
name|setMinLabelScore
argument_list|(
literal|0.24
argument_list|)
expr_stmt|;
comment|//1/4 of the tokens
name|linkerConfig
operator|.
name|setMinMatchScore
argument_list|(
comment|//labelScore * token match factor
name|linkerConfig
operator|.
name|getMinLabelScore
argument_list|()
operator|*
name|linkerConfig
operator|.
name|getMinTokenMatchFactor
argument_list|()
argument_list|)
expr_stmt|;
name|linkerConfig
operator|.
name|setRedirectProcessingMode
argument_list|(
name|RedirectProcessingMode
operator|.
name|IGNORE
argument_list|)
expr_stmt|;
comment|//remove all type mappings
name|linkerConfig
operator|.
name|setDefaultDcType
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|Set
argument_list|<
name|UriRef
argument_list|>
name|mappedUris
init|=
operator|new
name|HashSet
argument_list|<
name|UriRef
argument_list|>
argument_list|(
name|linkerConfig
operator|.
name|getTypeMappings
argument_list|()
operator|.
name|keySet
argument_list|()
argument_list|)
decl_stmt|;
for|for
control|(
name|UriRef
name|mappedUri
range|:
name|mappedUris
control|)
block|{
name|linkerConfig
operator|.
name|setTypeMapping
argument_list|(
name|mappedUri
operator|.
name|getUnicodeString
argument_list|()
argument_list|,
literal|null
argument_list|)
expr_stmt|;
block|}
comment|//parse confidence adjustment value (STANBOL-1219)
name|Object
name|value
init|=
name|properties
operator|.
name|get
argument_list|(
name|ADJUST_EXISTING_SUGGESTION_CONFIDENCE
argument_list|)
decl_stmt|;
specifier|final
name|double
name|confidenceAdjustment
decl_stmt|;
if|if
condition|(
name|value
operator|==
literal|null
condition|)
block|{
name|confidenceAdjustment
operator|=
name|DEFAULT_CONFIDENCE_ADJUSTEMENT
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|value
operator|instanceof
name|Number
condition|)
block|{
name|confidenceAdjustment
operator|=
operator|(
operator|(
name|Number
operator|)
name|value
operator|)
operator|.
name|doubleValue
argument_list|()
expr_stmt|;
block|}
else|else
block|{
try|try
block|{
name|confidenceAdjustment
operator|=
name|Double
operator|.
name|parseDouble
argument_list|(
name|value
operator|.
name|toString
argument_list|()
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|NumberFormatException
name|e
parameter_list|)
block|{
throw|throw
operator|new
name|ConfigurationException
argument_list|(
name|ADJUST_EXISTING_SUGGESTION_CONFIDENCE
argument_list|,
literal|"The confidence adjustement value for existing suggestions "
operator|+
literal|"MUST BE a double value in the range [0..1)"
argument_list|,
name|e
argument_list|)
throw|;
block|}
block|}
if|if
condition|(
name|confidenceAdjustment
operator|<
literal|0
operator|||
name|confidenceAdjustment
operator|>=
literal|1
condition|)
block|{
throw|throw
operator|new
name|ConfigurationException
argument_list|(
name|ADJUST_EXISTING_SUGGESTION_CONFIDENCE
argument_list|,
literal|"The confidence adjustement value for existing suggestions "
operator|+
literal|"MUST BE a double value in the range [0..1) (parsed: "
operator|+
name|confidenceAdjustment
operator|+
literal|")!"
argument_list|)
throw|;
block|}
name|confidenceAdjustmentFactor
operator|=
literal|1
operator|-
name|confidenceAdjustment
expr_stmt|;
comment|//get the metadata later set to the enhancement engine
block|}
comment|/**      * Deactivates this components.       */
annotation|@
name|Deactivate
specifier|protected
name|void
name|deactivate
parameter_list|(
name|ComponentContext
name|ctx
parameter_list|)
block|{
name|log
operator|.
name|info
argument_list|(
literal|"deactivate {}[name:{}]"
argument_list|,
name|getClass
argument_list|()
operator|.
name|getSimpleName
argument_list|()
argument_list|,
name|getName
argument_list|()
argument_list|)
expr_stmt|;
name|textProcessingConfig
operator|=
literal|null
expr_stmt|;
name|linkerConfig
operator|=
literal|null
expr_stmt|;
name|super
operator|.
name|deactivate
argument_list|(
name|ctx
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|int
name|canEnhance
parameter_list|(
name|ContentItem
name|ci
parameter_list|)
throws|throws
name|EngineException
block|{
name|String
name|language
init|=
name|getLanguage
argument_list|(
name|this
argument_list|,
name|ci
argument_list|,
literal|false
argument_list|)
decl_stmt|;
if|if
condition|(
name|language
operator|==
literal|null
operator|||
name|textProcessingConfig
operator|.
name|getConfiguration
argument_list|(
name|language
argument_list|)
operator|==
literal|null
condition|)
block|{
name|log
operator|.
name|debug
argument_list|(
literal|"Engine {} ignores ContentItem {} becuase language {} is not condigured."
argument_list|,
operator|new
name|Object
index|[]
block|{
name|getName
argument_list|()
block|,
name|ci
operator|.
name|getUri
argument_list|()
block|,
name|language
block|}
argument_list|)
expr_stmt|;
return|return
name|CANNOT_ENHANCE
return|;
block|}
comment|//we need a detected language, the AnalyzedText contentPart with Tokens.
name|AnalysedText
name|at
init|=
name|getAnalysedText
argument_list|(
name|this
argument_list|,
name|ci
argument_list|,
literal|false
argument_list|)
decl_stmt|;
return|return
name|at
operator|!=
literal|null
operator|&&
name|at
operator|.
name|getTokens
argument_list|()
operator|.
name|hasNext
argument_list|()
condition|?
name|ENHANCE_ASYNC
else|:
name|CANNOT_ENHANCE
return|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|computeEnhancements
parameter_list|(
name|ContentItem
name|ci
parameter_list|)
throws|throws
name|EngineException
block|{
name|AnalysedText
name|at
init|=
name|getAnalysedText
argument_list|(
name|this
argument_list|,
name|ci
argument_list|,
literal|true
argument_list|)
decl_stmt|;
name|String
name|language
init|=
name|getLanguage
argument_list|(
name|this
argument_list|,
name|ci
argument_list|,
literal|true
argument_list|)
decl_stmt|;
name|LanguageProcessingConfig
name|languageConfig
init|=
name|textProcessingConfig
operator|.
name|getConfiguration
argument_list|(
name|language
argument_list|)
decl_stmt|;
if|if
condition|(
name|languageConfig
operator|==
literal|null
condition|)
block|{
throw|throw
operator|new
name|IllegalStateException
argument_list|(
literal|"The language '"
operator|+
name|language
operator|+
literal|"' is not configured "
operator|+
literal|"to be processed by this Engine. As this is already checked within the "
operator|+
literal|"canEnhance(..) method this may indicate an bug in the used "
operator|+
literal|"EnhanceemntJobManager implementation!"
argument_list|)
throw|;
block|}
if|if
condition|(
name|log
operator|.
name|isDebugEnabled
argument_list|()
condition|)
block|{
name|log
operator|.
name|debug
argument_list|(
literal|"compute co-mentions for ContentItem {} language {}  text={}"
argument_list|,
operator|new
name|Object
index|[]
block|{
name|ci
operator|.
name|getUri
argument_list|()
operator|.
name|getUnicodeString
argument_list|()
block|,
name|language
block|,
name|StringUtils
operator|.
name|abbreviate
argument_list|(
name|at
operator|.
name|getSpan
argument_list|()
argument_list|,
literal|100
argument_list|)
block|}
argument_list|)
expr_stmt|;
block|}
comment|//create the in-memory database for the mentioned Entities
name|ContentItemMentionBuilder
name|entityMentionIndex
init|=
operator|new
name|ContentItemMentionBuilder
argument_list|(
name|labelTokenizer
argument_list|,
name|language
argument_list|,
name|linkerConfig
operator|.
name|getDefaultLanguage
argument_list|()
argument_list|)
decl_stmt|;
name|MGraph
name|metadata
init|=
name|ci
operator|.
name|getMetadata
argument_list|()
decl_stmt|;
name|Set
argument_list|<
name|UriRef
argument_list|>
name|textAnnotations
init|=
operator|new
name|HashSet
argument_list|<
name|UriRef
argument_list|>
argument_list|()
decl_stmt|;
name|ci
operator|.
name|getLock
argument_list|()
operator|.
name|readLock
argument_list|()
operator|.
name|lock
argument_list|()
expr_stmt|;
try|try
block|{
comment|//iterate over all TextAnnotations (mentions of Entities)
for|for
control|(
name|Iterator
argument_list|<
name|Triple
argument_list|>
name|it
init|=
name|metadata
operator|.
name|filter
argument_list|(
literal|null
argument_list|,
name|RDF_TYPE
argument_list|,
name|ENHANCER_TEXTANNOTATION
argument_list|)
init|;
name|it
operator|.
name|hasNext
argument_list|()
condition|;
control|)
block|{
name|UriRef
name|ta
init|=
operator|(
name|UriRef
operator|)
name|it
operator|.
name|next
argument_list|()
operator|.
name|getSubject
argument_list|()
decl_stmt|;
name|entityMentionIndex
operator|.
name|registerTextAnnotation
argument_list|(
name|ta
argument_list|,
name|metadata
argument_list|)
expr_stmt|;
name|textAnnotations
operator|.
name|add
argument_list|(
name|ta
argument_list|)
expr_stmt|;
comment|//store the registered text annotations
block|}
block|}
finally|finally
block|{
name|ci
operator|.
name|getLock
argument_list|()
operator|.
name|readLock
argument_list|()
operator|.
name|unlock
argument_list|()
expr_stmt|;
block|}
name|EntityLinker
name|entityLinker
init|=
operator|new
name|EntityLinker
argument_list|(
name|at
argument_list|,
name|language
argument_list|,
name|languageConfig
argument_list|,
name|entityMentionIndex
argument_list|,
name|linkerConfig
argument_list|,
name|labelTokenizer
argument_list|,
name|entityMentionIndex
argument_list|)
decl_stmt|;
comment|//process
try|try
block|{
name|entityLinker
operator|.
name|process
argument_list|()
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|EntitySearcherException
name|e
parameter_list|)
block|{
name|log
operator|.
name|error
argument_list|(
literal|"Unable to link Entities with "
operator|+
name|entityLinker
argument_list|,
name|e
argument_list|)
expr_stmt|;
throw|throw
operator|new
name|EngineException
argument_list|(
name|this
argument_list|,
name|ci
argument_list|,
literal|"Unable to link Entities with "
operator|+
name|entityLinker
argument_list|,
name|e
argument_list|)
throw|;
block|}
comment|//TODO: write results
name|ci
operator|.
name|getLock
argument_list|()
operator|.
name|writeLock
argument_list|()
operator|.
name|lock
argument_list|()
expr_stmt|;
try|try
block|{
name|writeComentions
argument_list|(
name|ci
argument_list|,
name|entityLinker
operator|.
name|getLinkedEntities
argument_list|()
operator|.
name|values
argument_list|()
argument_list|,
name|language
argument_list|,
name|textAnnotations
argument_list|)
expr_stmt|;
block|}
finally|finally
block|{
name|ci
operator|.
name|getLock
argument_list|()
operator|.
name|writeLock
argument_list|()
operator|.
name|unlock
argument_list|()
expr_stmt|;
block|}
block|}
specifier|private
name|void
name|writeComentions
parameter_list|(
name|ContentItem
name|ci
parameter_list|,
name|Collection
argument_list|<
name|LinkedEntity
argument_list|>
name|comentions
parameter_list|,
name|String
name|language
parameter_list|,
name|Set
argument_list|<
name|UriRef
argument_list|>
name|textAnnotations
parameter_list|)
block|{
name|Language
name|languageObject
init|=
literal|null
decl_stmt|;
if|if
condition|(
name|language
operator|!=
literal|null
operator|&&
operator|!
name|language
operator|.
name|isEmpty
argument_list|()
condition|)
block|{
name|languageObject
operator|=
operator|new
name|Language
argument_list|(
name|language
argument_list|)
expr_stmt|;
block|}
name|MGraph
name|metadata
init|=
name|ci
operator|.
name|getMetadata
argument_list|()
decl_stmt|;
comment|//we MUST adjust the confidence level of existing annotations only once
comment|//se we need to keep track of those
name|Set
argument_list|<
name|NonLiteral
argument_list|>
name|adjustedSuggestions
init|=
operator|new
name|HashSet
argument_list|<
name|NonLiteral
argument_list|>
argument_list|()
decl_stmt|;
name|log
operator|.
name|debug
argument_list|(
literal|"Write Co-Mentions:"
argument_list|)
expr_stmt|;
for|for
control|(
name|LinkedEntity
name|comention
range|:
name|comentions
control|)
block|{
name|log
operator|.
name|debug
argument_list|(
literal|"> {}"
argument_list|,
name|comention
argument_list|)
expr_stmt|;
comment|//URIs of TextAnnotations for the initial mention of this co-mention
name|Collection
argument_list|<
name|UriRef
argument_list|>
name|initialMentions
init|=
operator|new
name|ArrayList
argument_list|<
name|UriRef
argument_list|>
argument_list|(
name|comention
operator|.
name|getSuggestions
argument_list|()
operator|.
name|size
argument_list|()
argument_list|)
decl_stmt|;
for|for
control|(
name|Suggestion
name|suggestion
range|:
name|comention
operator|.
name|getSuggestions
argument_list|()
control|)
block|{
name|Entity
name|entity
init|=
name|suggestion
operator|.
name|getEntity
argument_list|()
decl_stmt|;
if|if
condition|(
name|textAnnotations
operator|.
name|contains
argument_list|(
name|entity
operator|.
name|getUri
argument_list|()
argument_list|)
condition|)
block|{
comment|//                if(entity.getData().filter(entity.getUri(),RDF_TYPE,ENHANCER_TEXTANNOTATION).hasNext()){
comment|//this is a textAnnotation
name|initialMentions
operator|.
name|add
argument_list|(
name|entity
operator|.
name|getUri
argument_list|()
argument_list|)
expr_stmt|;
block|}
comment|//else TODO support also Entities!!
block|}
comment|//create the TextAnnotations for the co-mention
for|for
control|(
name|Occurrence
name|occurrence
range|:
name|comention
operator|.
name|getOccurrences
argument_list|()
control|)
block|{
name|Literal
name|startLiteral
init|=
name|literalFactory
operator|.
name|createTypedLiteral
argument_list|(
name|occurrence
operator|.
name|getStart
argument_list|()
argument_list|)
decl_stmt|;
name|Literal
name|endLiteral
init|=
name|literalFactory
operator|.
name|createTypedLiteral
argument_list|(
name|occurrence
operator|.
name|getEnd
argument_list|()
argument_list|)
decl_stmt|;
comment|//search for existing text annotation
name|boolean
name|ignore
init|=
literal|false
decl_stmt|;
comment|//search for textAnnotations with the same end
name|UriRef
name|textAnnotation
init|=
literal|null
decl_stmt|;
name|Iterator
argument_list|<
name|Triple
argument_list|>
name|it
init|=
name|metadata
operator|.
name|filter
argument_list|(
literal|null
argument_list|,
name|ENHANCER_START
argument_list|,
name|startLiteral
argument_list|)
decl_stmt|;
while|while
condition|(
name|it
operator|.
name|hasNext
argument_list|()
condition|)
block|{
name|Triple
name|t
init|=
name|it
operator|.
name|next
argument_list|()
decl_stmt|;
name|Integer
name|end
init|=
name|EnhancementEngineHelper
operator|.
name|get
argument_list|(
name|metadata
argument_list|,
name|t
operator|.
name|getSubject
argument_list|()
argument_list|,
name|ENHANCER_END
argument_list|,
name|Integer
operator|.
name|class
argument_list|,
name|literalFactory
argument_list|)
decl_stmt|;
if|if
condition|(
name|end
operator|!=
literal|null
operator|&&
name|textAnnotations
operator|.
name|contains
argument_list|(
name|t
operator|.
name|getSubject
argument_list|()
argument_list|)
condition|)
block|{
comment|//metadata.filter(t.getSubject(), RDF_TYPE, ENHANCER_TEXTANNOTATION).hasNext()){
name|textAnnotation
operator|=
operator|(
name|UriRef
operator|)
name|t
operator|.
name|getSubject
argument_list|()
expr_stmt|;
if|if
condition|(
name|end
operator|>
name|occurrence
operator|.
name|getEnd
argument_list|()
condition|)
block|{
comment|// there is an other TextAnnotation selecting a bigger Span
comment|//so we should ignore this Occurrence
name|ignore
operator|=
literal|true
expr_stmt|;
block|}
block|}
block|}
name|it
operator|=
name|metadata
operator|.
name|filter
argument_list|(
literal|null
argument_list|,
name|ENHANCER_END
argument_list|,
name|endLiteral
argument_list|)
expr_stmt|;
while|while
condition|(
name|it
operator|.
name|hasNext
argument_list|()
condition|)
block|{
name|Triple
name|t
init|=
name|it
operator|.
name|next
argument_list|()
decl_stmt|;
name|Integer
name|start
init|=
name|EnhancementEngineHelper
operator|.
name|get
argument_list|(
name|metadata
argument_list|,
name|t
operator|.
name|getSubject
argument_list|()
argument_list|,
name|ENHANCER_START
argument_list|,
name|Integer
operator|.
name|class
argument_list|,
name|literalFactory
argument_list|)
decl_stmt|;
if|if
condition|(
name|start
operator|!=
literal|null
operator|&&
name|textAnnotations
operator|.
name|contains
argument_list|(
name|t
operator|.
name|getSubject
argument_list|()
argument_list|)
condition|)
block|{
comment|//metadata.filter(t.getSubject(), RDF_TYPE, ENHANCER_TEXTANNOTATION).hasNext()){
name|textAnnotation
operator|=
operator|(
name|UriRef
operator|)
name|t
operator|.
name|getSubject
argument_list|()
expr_stmt|;
if|if
condition|(
name|start
operator|<
name|occurrence
operator|.
name|getStart
argument_list|()
condition|)
block|{
comment|// there is an other TextAnnotation selecting a bigger Span
comment|//so we should ignore this Occurrence
name|ignore
operator|=
literal|true
expr_stmt|;
block|}
block|}
block|}
if|if
condition|(
operator|!
name|ignore
condition|)
block|{
comment|//collect confidence values of co-mentions
name|Double
name|maxConfidence
init|=
literal|null
decl_stmt|;
comment|//maximum confidence of suggestions of the initial mention
name|Double
name|maxExistingConfidence
init|=
literal|null
decl_stmt|;
comment|//maximum confidence of existing suggestions
if|if
condition|(
name|textAnnotation
operator|==
literal|null
condition|)
block|{
comment|//not found ... create a new TextAnnotation for the co-mention
name|textAnnotation
operator|=
name|EnhancementEngineHelper
operator|.
name|createTextEnhancement
argument_list|(
name|ci
argument_list|,
name|this
argument_list|)
expr_stmt|;
name|textAnnotations
operator|.
name|add
argument_list|(
name|textAnnotation
argument_list|)
expr_stmt|;
comment|//add it to the set of TextAnnotations
name|metadata
operator|.
name|add
argument_list|(
operator|new
name|TripleImpl
argument_list|(
name|textAnnotation
argument_list|,
name|Properties
operator|.
name|ENHANCER_START
argument_list|,
name|startLiteral
argument_list|)
argument_list|)
expr_stmt|;
name|metadata
operator|.
name|add
argument_list|(
operator|new
name|TripleImpl
argument_list|(
name|textAnnotation
argument_list|,
name|Properties
operator|.
name|ENHANCER_END
argument_list|,
name|endLiteral
argument_list|)
argument_list|)
expr_stmt|;
name|metadata
operator|.
name|add
argument_list|(
operator|new
name|TripleImpl
argument_list|(
name|textAnnotation
argument_list|,
name|Properties
operator|.
name|ENHANCER_SELECTION_CONTEXT
argument_list|,
operator|new
name|PlainLiteralImpl
argument_list|(
name|occurrence
operator|.
name|getContext
argument_list|()
argument_list|,
name|languageObject
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
name|metadata
operator|.
name|add
argument_list|(
operator|new
name|TripleImpl
argument_list|(
name|textAnnotation
argument_list|,
name|Properties
operator|.
name|ENHANCER_SELECTED_TEXT
argument_list|,
operator|new
name|PlainLiteralImpl
argument_list|(
name|occurrence
operator|.
name|getSelectedText
argument_list|()
argument_list|,
name|languageObject
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
block|}
else|else
block|{
comment|//if existing add this engine as contributor
name|metadata
operator|.
name|add
argument_list|(
operator|new
name|TripleImpl
argument_list|(
name|textAnnotation
argument_list|,
name|DC_CONTRIBUTOR
argument_list|,
operator|new
name|PlainLiteralImpl
argument_list|(
name|this
operator|.
name|getClass
argument_list|()
operator|.
name|getName
argument_list|()
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
comment|//maxConfidence = EnhancementEngineHelper.get(metadata, textAnnotation,
comment|//    ENHANCER_CONFIDENCE, Double.class, literalFactory);
block|}
comment|//now process initial mention(s) for the co-mention
name|Set
argument_list|<
name|UriRef
argument_list|>
name|dcTypes
init|=
operator|new
name|HashSet
argument_list|<
name|UriRef
argument_list|>
argument_list|()
decl_stmt|;
for|for
control|(
name|UriRef
name|initialMention
range|:
name|initialMentions
control|)
block|{
comment|//get the dc:type(s) of the initial mentions
name|Iterator
argument_list|<
name|UriRef
argument_list|>
name|dcTypesIt
init|=
name|getReferences
argument_list|(
name|metadata
argument_list|,
name|initialMention
argument_list|,
name|DC_TYPE
argument_list|)
decl_stmt|;
while|while
condition|(
name|dcTypesIt
operator|.
name|hasNext
argument_list|()
condition|)
block|{
name|dcTypes
operator|.
name|add
argument_list|(
name|dcTypesIt
operator|.
name|next
argument_list|()
argument_list|)
expr_stmt|;
block|}
comment|//check confidence of the initial mention (fise:TextAnnotation)
name|Double
name|confidnece
init|=
name|EnhancementEngineHelper
operator|.
name|get
argument_list|(
name|metadata
argument_list|,
name|initialMention
argument_list|,
name|ENHANCER_CONFIDENCE
argument_list|,
name|Double
operator|.
name|class
argument_list|,
name|literalFactory
argument_list|)
decl_stmt|;
if|if
condition|(
name|confidnece
operator|!=
literal|null
condition|)
block|{
if|if
condition|(
name|maxConfidence
operator|==
literal|null
condition|)
block|{
name|maxConfidence
operator|=
name|confidnece
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|maxConfidence
operator|.
name|compareTo
argument_list|(
name|confidnece
argument_list|)
operator|<=
literal|0
condition|)
block|{
name|maxConfidence
operator|=
name|confidnece
expr_stmt|;
block|}
block|}
comment|//else nothing to do
comment|//now we need to compare the suggestions of the initial
comment|//mention(s) with the existing one.
comment|//Get information about the suggestions of the initial mention
name|Map
argument_list|<
name|Resource
argument_list|,
name|Double
argument_list|>
name|initialSuggestions
init|=
operator|new
name|HashMap
argument_list|<
name|Resource
argument_list|,
name|Double
argument_list|>
argument_list|()
decl_stmt|;
name|Map
argument_list|<
name|Resource
argument_list|,
name|Resource
argument_list|>
name|initialSuggestedEntities
init|=
operator|new
name|HashMap
argument_list|<
name|Resource
argument_list|,
name|Resource
argument_list|>
argument_list|()
decl_stmt|;
for|for
control|(
name|Iterator
argument_list|<
name|Triple
argument_list|>
name|suggestions
init|=
name|metadata
operator|.
name|filter
argument_list|(
literal|null
argument_list|,
name|DC_RELATION
argument_list|,
name|initialMention
argument_list|)
init|;
name|suggestions
operator|.
name|hasNext
argument_list|()
condition|;
control|)
block|{
if|if
condition|(
operator|!
name|textAnnotations
operator|.
name|contains
argument_list|(
name|suggestions
argument_list|)
condition|)
block|{
name|NonLiteral
name|suggestion
init|=
name|suggestions
operator|.
name|next
argument_list|()
operator|.
name|getSubject
argument_list|()
decl_stmt|;
name|Resource
name|suggestedEntity
init|=
name|EnhancementEngineHelper
operator|.
name|getReference
argument_list|(
name|metadata
argument_list|,
name|suggestion
argument_list|,
name|ENHANCER_ENTITY_REFERENCE
argument_list|)
decl_stmt|;
if|if
condition|(
name|suggestedEntity
operator|!=
literal|null
condition|)
block|{
comment|//it has a suggestion
name|Double
name|confidence
init|=
name|EnhancementEngineHelper
operator|.
name|get
argument_list|(
name|metadata
argument_list|,
name|suggestion
argument_list|,
name|ENHANCER_CONFIDENCE
argument_list|,
name|Double
operator|.
name|class
argument_list|,
name|literalFactory
argument_list|)
decl_stmt|;
if|if
condition|(
name|maxConfidence
operator|==
literal|null
condition|)
block|{
name|maxConfidence
operator|=
name|confidence
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|confidnece
operator|!=
literal|null
operator|&&
name|maxConfidence
operator|.
name|compareTo
argument_list|(
name|confidnece
argument_list|)
operator|<=
literal|0
condition|)
block|{
name|maxConfidence
operator|=
name|confidnece
expr_stmt|;
block|}
comment|//else nothing to do
name|initialSuggestions
operator|.
name|put
argument_list|(
name|suggestion
argument_list|,
name|confidence
argument_list|)
expr_stmt|;
name|initialSuggestedEntities
operator|.
name|put
argument_list|(
name|suggestedEntity
argument_list|,
name|suggestion
argument_list|)
expr_stmt|;
block|}
comment|//no suggestion (dc:relation to some other resource)
block|}
comment|// else ignore dc:relation to other fise:TextAnnotations
block|}
comment|//now we collect existing Suggestions for this TextAnnoation where we need
comment|//to adjust the confidence (quite some things to check ....)
name|Map
argument_list|<
name|NonLiteral
argument_list|,
name|Double
argument_list|>
name|existingSuggestions
init|=
operator|new
name|HashMap
argument_list|<
name|NonLiteral
argument_list|,
name|Double
argument_list|>
argument_list|()
decl_stmt|;
if|if
condition|(
name|maxConfidence
operator|!=
literal|null
operator|&&
name|confidenceAdjustmentFactor
operator|<
literal|1
condition|)
block|{
comment|//suggestions are defined by incoming dc:releation
for|for
control|(
name|Iterator
argument_list|<
name|Triple
argument_list|>
name|esIt
init|=
name|metadata
operator|.
name|filter
argument_list|(
literal|null
argument_list|,
name|DC_RELATION
argument_list|,
name|textAnnotation
argument_list|)
init|;
name|esIt
operator|.
name|hasNext
argument_list|()
condition|;
control|)
block|{
name|NonLiteral
name|existingSuggestion
init|=
name|esIt
operator|.
name|next
argument_list|()
operator|.
name|getSubject
argument_list|()
decl_stmt|;
comment|//but not all of them are suggestions
if|if
condition|(
operator|!
name|textAnnotations
operator|.
name|contains
argument_list|(
name|existingSuggestion
argument_list|)
condition|)
block|{
comment|//ignore fise:TextAnnotations
name|Double
name|existingConfidence
init|=
name|EnhancementEngineHelper
operator|.
name|get
argument_list|(
name|metadata
argument_list|,
name|existingSuggestion
argument_list|,
name|ENHANCER_CONFIDENCE
argument_list|,
name|Double
operator|.
name|class
argument_list|,
name|literalFactory
argument_list|)
decl_stmt|;
comment|//ignore fise:TextAnnotations also suggested for the initial mention
if|if
condition|(
operator|!
name|initialSuggestions
operator|.
name|containsKey
argument_list|(
name|existingSuggestion
argument_list|)
condition|)
block|{
name|Resource
name|suggestedEntity
init|=
name|EnhancementEngineHelper
operator|.
name|getReference
argument_list|(
name|metadata
argument_list|,
name|existingSuggestion
argument_list|,
name|ENHANCER_ENTITY_REFERENCE
argument_list|)
decl_stmt|;
comment|//we might also have different fise:TextAnnotations that
comment|//fise:entity-reference to an Entity present in the
comment|//suggestions for the initial mention
if|if
condition|(
operator|!
name|initialSuggestedEntities
operator|.
name|containsKey
argument_list|(
name|suggestedEntity
argument_list|)
condition|)
block|{
comment|//finally make sure that we adjust confidences only once
if|if
condition|(
operator|!
name|adjustedSuggestions
operator|.
name|contains
argument_list|(
name|existingSuggestion
argument_list|)
condition|)
block|{
name|existingSuggestions
operator|.
name|put
argument_list|(
name|existingSuggestion
argument_list|,
name|existingConfidence
argument_list|)
expr_stmt|;
block|}
comment|//else confidence already adjusted
block|}
else|else
block|{
comment|// different fise:EntityAnnotation, but same reference Entity
comment|//we need to check confidences to decide what to do
name|Resource
name|initialSuggestion
init|=
name|initialSuggestedEntities
operator|.
name|get
argument_list|(
name|suggestedEntity
argument_list|)
decl_stmt|;
name|Double
name|initialConfidence
init|=
name|initialSuggestions
operator|.
name|get
argument_list|(
name|initialSuggestion
argument_list|)
decl_stmt|;
if|if
condition|(
name|initialConfidence
operator|==
literal|null
operator|||
operator|(
name|existingConfidence
operator|!=
literal|null
operator|&&
name|existingConfidence
operator|.
name|compareTo
argument_list|(
name|initialConfidence
argument_list|)
operator|>=
literal|0
operator|)
condition|)
block|{
comment|//existing confidence>= initial .. keep existing
name|initialSuggestions
operator|.
name|remove
argument_list|(
name|initialSuggestion
argument_list|)
expr_stmt|;
if|if
condition|(
name|maxExistingConfidence
operator|==
literal|null
condition|)
block|{
name|maxExistingConfidence
operator|=
name|existingConfidence
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|maxExistingConfidence
operator|.
name|compareTo
argument_list|(
name|existingConfidence
argument_list|)
operator|<=
literal|0
condition|)
block|{
name|maxExistingConfidence
operator|=
name|existingConfidence
expr_stmt|;
block|}
block|}
else|else
block|{
comment|//initial has higher confidence
comment|//adjust this one (if not yet adjusted)
if|if
condition|(
operator|!
name|adjustedSuggestions
operator|.
name|contains
argument_list|(
name|existingSuggestion
argument_list|)
condition|)
block|{
name|existingSuggestions
operator|.
name|put
argument_list|(
name|existingSuggestion
argument_list|,
name|existingConfidence
argument_list|)
expr_stmt|;
block|}
block|}
block|}
block|}
else|else
block|{
comment|//a initial mention already present
comment|//no need to process initial mention
name|initialSuggestions
operator|.
name|remove
argument_list|(
name|existingSuggestion
argument_list|)
expr_stmt|;
if|if
condition|(
name|maxExistingConfidence
operator|==
literal|null
condition|)
block|{
name|maxExistingConfidence
operator|=
name|existingConfidence
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|existingConfidence
operator|!=
literal|null
operator|&&
name|maxExistingConfidence
operator|.
name|compareTo
argument_list|(
name|existingConfidence
argument_list|)
operator|<=
literal|0
condition|)
block|{
name|maxExistingConfidence
operator|=
name|existingConfidence
expr_stmt|;
block|}
comment|//else maxExistingConfidence == null (undefined)
block|}
block|}
comment|//else ignore dc:relations to other fise:TextAnnotations
block|}
for|for
control|(
name|Entry
argument_list|<
name|NonLiteral
argument_list|,
name|Double
argument_list|>
name|entry
range|:
name|existingSuggestions
operator|.
name|entrySet
argument_list|()
control|)
block|{
if|if
condition|(
name|entry
operator|.
name|getValue
argument_list|()
operator|!=
literal|null
condition|)
block|{
name|double
name|adjustedConfidence
init|=
name|entry
operator|.
name|getValue
argument_list|()
operator|*
name|confidenceAdjustmentFactor
decl_stmt|;
if|if
condition|(
name|maxExistingConfidence
operator|==
literal|null
operator|||
name|adjustedConfidence
operator|>
name|maxExistingConfidence
condition|)
block|{
name|maxExistingConfidence
operator|=
name|adjustedConfidence
expr_stmt|;
block|}
name|EnhancementEngineHelper
operator|.
name|set
argument_list|(
name|metadata
argument_list|,
name|entry
operator|.
name|getKey
argument_list|()
argument_list|,
name|ENHANCER_CONFIDENCE
argument_list|,
name|adjustedConfidence
argument_list|,
name|literalFactory
argument_list|)
expr_stmt|;
name|adjustedSuggestions
operator|.
name|add
argument_list|(
name|entry
operator|.
name|getKey
argument_list|()
argument_list|)
expr_stmt|;
comment|//mark as adjusted
block|}
block|}
block|}
comment|//add the suggestions of the initial mention to this one
for|for
control|(
name|Resource
name|suggestion
range|:
name|initialSuggestions
operator|.
name|keySet
argument_list|()
control|)
block|{
name|metadata
operator|.
name|add
argument_list|(
operator|new
name|TripleImpl
argument_list|(
operator|(
name|NonLiteral
operator|)
name|suggestion
argument_list|,
name|DC_RELATION
argument_list|,
name|textAnnotation
argument_list|)
argument_list|)
expr_stmt|;
block|}
comment|//finally link the co-mentation with the initial one
name|metadata
operator|.
name|add
argument_list|(
operator|new
name|TripleImpl
argument_list|(
name|textAnnotation
argument_list|,
name|DC_RELATION
argument_list|,
name|initialMention
argument_list|)
argument_list|)
expr_stmt|;
comment|//metadata.add(new TripleImpl(initialMention, DC_RELATION, textAnnotation));
block|}
comment|// Adapt the dc:type values of the fise:TextAnnotation
comment|// - if Suggestions added by this engine do have the max confidence
comment|//   use the dc:type values of the initial mention
comment|// - if the original suggestions do have a higher confidence keep the
comment|//   existing
comment|// - in case both do have the same confidence we add all dc:types
name|boolean
name|removeExistingDcTypes
init|=
name|maxConfidence
operator|!=
literal|null
operator|&&
operator|(
name|maxExistingConfidence
operator|==
literal|null
operator|||
name|maxConfidence
operator|.
name|compareTo
argument_list|(
name|maxExistingConfidence
argument_list|)
operator|>=
literal|0
operator|)
decl_stmt|;
name|boolean
name|addCoMentionDcTypes
init|=
name|maxExistingConfidence
operator|==
literal|null
operator|||
operator|(
name|maxConfidence
operator|!=
literal|null
operator|&&
name|maxConfidence
operator|.
name|compareTo
argument_list|(
name|maxExistingConfidence
argument_list|)
operator|>=
literal|1
operator|)
decl_stmt|;
name|Iterator
argument_list|<
name|UriRef
argument_list|>
name|existingDcTypesIt
init|=
name|getReferences
argument_list|(
name|metadata
argument_list|,
name|textAnnotation
argument_list|,
name|DC_TYPE
argument_list|)
decl_stmt|;
while|while
condition|(
name|existingDcTypesIt
operator|.
name|hasNext
argument_list|()
condition|)
block|{
comment|//do not add existing
comment|//remove dc:type triples if they are not re-added later and
comment|//removeExistingDcTypes == true
if|if
condition|(
operator|(
operator|!
name|dcTypes
operator|.
name|remove
argument_list|(
name|existingDcTypesIt
operator|.
name|next
argument_list|()
argument_list|)
operator|||
operator|!
name|addCoMentionDcTypes
operator|)
operator|&&
name|removeExistingDcTypes
condition|)
block|{
name|existingDcTypesIt
operator|.
name|remove
argument_list|()
expr_stmt|;
comment|//remove the dcType
block|}
block|}
if|if
condition|(
name|addCoMentionDcTypes
condition|)
block|{
for|for
control|(
name|UriRef
name|dcType
range|:
name|dcTypes
control|)
block|{
comment|//add missing
name|metadata
operator|.
name|add
argument_list|(
operator|new
name|TripleImpl
argument_list|(
name|textAnnotation
argument_list|,
name|DC_TYPE
argument_list|,
name|dcType
argument_list|)
argument_list|)
expr_stmt|;
block|}
block|}
comment|//TODO: support also Entities
if|if
condition|(
name|maxConfidence
operator|!=
literal|null
condition|)
block|{
comment|//set the confidence value (if known)
name|EnhancementEngineHelper
operator|.
name|set
argument_list|(
name|metadata
argument_list|,
name|textAnnotation
argument_list|,
name|ENHANCER_CONFIDENCE
argument_list|,
name|maxConfidence
argument_list|,
name|literalFactory
argument_list|)
expr_stmt|;
block|}
block|}
comment|//else ignore this occurence
block|}
block|}
block|}
annotation|@
name|Override
specifier|public
name|Map
argument_list|<
name|String
argument_list|,
name|Object
argument_list|>
name|getServiceProperties
parameter_list|()
block|{
return|return
name|SERVICE_PROPERTIES
return|;
block|}
block|}
end_class

end_unit

