begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|owl
package|;
end_package

begin_import
import|import
name|java
operator|.
name|net
operator|.
name|URISyntaxException
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Set
import|;
end_import

begin_import
import|import
name|org
operator|.
name|semanticweb
operator|.
name|owlapi
operator|.
name|model
operator|.
name|IRI
import|;
end_import

begin_import
import|import
name|org
operator|.
name|semanticweb
operator|.
name|owlapi
operator|.
name|model
operator|.
name|OWLOntologyIRIMapper
import|;
end_import

begin_class
specifier|public
class|class
name|PhonyIRIMapper
implements|implements
name|OWLOntologyIRIMapper
block|{
specifier|private
name|Set
argument_list|<
name|IRI
argument_list|>
name|notMapped
decl_stmt|;
specifier|private
name|IRI
name|blankIri
init|=
literal|null
decl_stmt|;
specifier|private
name|String
name|blankResourcePath
init|=
literal|"/ontologies/blank.owl"
decl_stmt|;
specifier|public
name|PhonyIRIMapper
parameter_list|(
name|Set
argument_list|<
name|IRI
argument_list|>
name|notMapped
parameter_list|)
block|{
name|this
operator|.
name|notMapped
operator|=
name|notMapped
expr_stmt|;
try|try
block|{
name|blankIri
operator|=
name|IRI
operator|.
name|create
argument_list|(
name|this
operator|.
name|getClass
argument_list|()
operator|.
name|getResource
argument_list|(
name|blankResourcePath
argument_list|)
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|URISyntaxException
name|e
parameter_list|)
block|{
comment|// How can it happen?
block|}
block|}
annotation|@
name|Override
specifier|public
name|IRI
name|getDocumentIRI
parameter_list|(
name|IRI
name|arg0
parameter_list|)
block|{
if|if
condition|(
name|notMapped
operator|.
name|contains
argument_list|(
name|arg0
argument_list|)
condition|)
return|return
literal|null
return|;
else|else
return|return
name|blankIri
return|;
block|}
block|}
end_class

end_unit

