begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/* * Licensed to the Apache Software Foundation (ASF) under one or more * contributor license agreements.  See the NOTICE file distributed with * this work for additional information regarding copyright ownership. * The ASF licenses this file to You under the Apache License, Version 2.0 * (the "License"); you may not use this file except in compliance with * the License.  You may obtain a copy of the License at * *     http://www.apache.org/licenses/LICENSE-2.0 * * Unless required by applicable law or agreed to in writing, software * distributed under the License is distributed on an "AS IS" BASIS, * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. * See the License for the specific language governing permissions and * limitations under the License. */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|engines
operator|.
name|kuromoji
operator|.
name|impl
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|nlp
operator|.
name|ner
operator|.
name|NerTag
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|stanbol
operator|.
name|enhancer
operator|.
name|servicesapi
operator|.
name|ContentItem
import|;
end_import

begin_comment
comment|/**  * Used as intermediate representation of NER annotations so that one needs  * not to obtain a write lock on the {@link ContentItem} for each detected   * entity  * @author Rupert Westenthaler  *  */
end_comment

begin_class
class|class
name|NerData
block|{
specifier|protected
specifier|final
name|NerTag
name|tag
decl_stmt|;
specifier|protected
specifier|final
name|int
name|start
decl_stmt|;
specifier|protected
name|int
name|end
decl_stmt|;
specifier|protected
name|String
name|context
decl_stmt|;
specifier|protected
name|NerData
parameter_list|(
name|NerTag
name|ner
parameter_list|,
name|int
name|start
parameter_list|)
block|{
name|this
operator|.
name|tag
operator|=
name|ner
expr_stmt|;
name|this
operator|.
name|start
operator|=
name|start
expr_stmt|;
block|}
block|}
end_class

end_unit

